<Project>
	<PropertyGroup>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
		<RoslynVersion>5.9.0</RoslynVersion>
		<TUnitVersion>1.67.0</TUnitVersion>
		<PurviewSGFVersion>1.0.0-prerelease.52</PurviewSGFVersion>
		<DotnetRuntimeVersion>10.0.12</DotnetRuntimeVersion>
		<MSExtensionVersion>10.10.0</MSExtensionVersion>
		<OpenTelemetryVersion>1.18.0</OpenTelemetryVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Purview.SourceGeneratorFramework" Version="$(PurviewSGFVersion)" />
		<PackageVersion Include="Purview.SourceGeneratorFramework.Testing.TUnit" Version="$(PurviewSGFVersion)" />
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(RoslynVersion)" />
		<PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="$(RoslynVersion)" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(RoslynVersion)" />
		<PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="$(RoslynVersion)" />
		<PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="$(RoslynVersion)" />
		<PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="$(DotnetRuntimeVersion)" />
		<PackageVersion Include="Microsoft.Extensions.Logging" Version="$(DotnetRuntimeVersion)" />
		<PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="$(DotnetRuntimeVersion)" />
		<PackageVersion Include="Microsoft.Extensions.Telemetry.Abstractions" Version="$(MSExtensionVersion)" />
		<PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="$(DotnetRuntimeVersion)" />
	</ItemGroup>
	<ItemGroup Label="Testing">
		<PackageVersion Include="TUnit" Version="$(TUnitVersion)" />
		<PackageVersion Include="TUnit.Mocks" Version="$(TUnitVersion)" />
		<PackageVersion Include="Bogus" Version="35.6.5" />
	</ItemGroup>
	<ItemGroup Label="Samples">
		<PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="$(DotnetRuntimeVersion)" />
		<PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="$(MSExtensionVersion)" />
		<PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="$(MSExtensionVersion)" />
		<PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="$(OpenTelemetryVersion)" />
		<PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="$(OpenTelemetryVersion)" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="$(OpenTelemetryVersion)" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.18.0-beta.1" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="$(OpenTelemetryVersion)" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.Process" Version="1.18.0-rc.1" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="$(OpenTelemetryVersion)" />
		<PackageVersion Include="Scalar.AspNetCore" Version="2.17.3" />
		<PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
		<PackageVersion Include="ErrorOr" Version="2.1.1" />
	</ItemGroup>
</Project>
