using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Purview.Telemetry.SourceGenerator.Helpers;
using Purview.Telemetry.SourceGenerator.Records;
using Purview.Telemetry.SourceGenerator.Templates;

namespace Purview.Telemetry.SourceGenerator.Emitters;

static partial class MultiTargetClassEmitter
{
	public static void GenerateImplementation(
		MultiTargetInterface targetInterface,
		SourceProductionContext context,
		GenerationLogger? logger
	)
	{
		var interfaceName = targetInterface.InterfaceName;
		var classNamespace = targetInterface.Namespace;

		var classNameToGenerate = targetInterface.TelemetryGeneration.ClassName.Or(
			GenerateClassName(interfaceName)
		);

		// Create a target record that follows the same pattern as other targets
		var target = new MultiTargetGenerationTarget(
			TelemetryGeneration: targetInterface.TelemetryGeneration,
			GenerationType: targetInterface.GenerationType,
			ClassNameToGenerate: classNameToGenerate,
			ClassNamespace: classNamespace,
			ParentClasses: targetInterface.ParentClasses,
			FullNamespace: string.IsNullOrEmpty(classNamespace) ? null : classNamespace + ".",
			FullyQualifiedName: (string.IsNullOrEmpty(classNamespace) ? "" : classNamespace + ".")
				+ classNameToGenerate,
			InterfaceType: PurviewTypeFactory.Create(targetInterface.InterfaceSymbol),
			Methods: targetInterface.Methods,
			DuplicateMethods: ImmutableDictionary<string, Location[]>.Empty,
			Failures: null
		);

		logger?.Debug($"Generating multi-target implementation for: {interfaceName}");

		var builder = new CodeWriter();
		var hintName = $"{target.FullyQualifiedName}.MultiTarget.g.cs";
		// Header & hint name: ensure single header only (LoadEmbeddedResource already injects header at top).
		builder
			.Append("//HintName: ")
			.Append(hintName)
			.AppendLine()
			.Append(EmbeddedResources.Instance.LoadEmbeddedResource("AutoGeneratedHeader"));

		var indent = EmitHelpers.EmitNamespaceStart(
			target.ClassNamespace,
			target.ParentClasses,
			builder,
			context.CancellationToken
		);

		indent = EmitHelpers.EmitClassStart(
			target.GenerationType,
			target.GenerationType,
			target.ClassNameToGenerate,
			target.InterfaceType.FullyQualifiedName,
			builder,
			indent,
			context.CancellationToken
		);

		EmitFields(target, builder, indent, context, logger);
		EmitConstructor(target, builder, indent, context, logger);
		EmitMethods(target, builder, indent, context, logger);

		EmitHelpers.EmitClassEnd(builder, indent);

		EmitHelpers.EmitNamespaceEnd(
			target.ClassNamespace,
			target.ParentClasses,
			indent,
			builder,
			context.CancellationToken
		);

		context.AddSource(
			hintName,
			Microsoft.CodeAnalysis.Text.SourceText.From(builder.ToString(), Encoding.UTF8)
		);

		// Emit DI helper for multi-target implementations as well
		DependencyInjectionClassEmitter.GenerateImplementation(
			/* requestingType */target.GenerationType,
			/* attribute */target.TelemetryGeneration,
			/* generationType */target.GenerationType,
			/* implementationClassName */target.ClassNameToGenerate,
			/* sourceInterfaceName */target.InterfaceType.TypeName,
			/* fullyQualifiedNamespace */target.FullNamespace,
			context,
			logger
		);
	}

	static string GenerateClassName(string name)
	{
		if (name[0] == 'I')
			name = name.Substring(1);

		return name + "Core";
	}

	public static string GenerateForBenchmark(MultiTargetGenerationTarget target)
	{
		var builder = new CodeWriter();
		builder.Write(EmbeddedResources.Instance.LoadEmbeddedResource("AutoGeneratedHeader"));
		var indent = EmitHelpers.EmitNamespaceStart(
			target.ClassNamespace,
			target.ParentClasses,
			builder,
			default
		);
		indent = EmitHelpers.EmitClassStart(
			/* generationType */target.GenerationType,
			/* requestingType */target.GenerationType,
			target.ClassNameToGenerate,
			target.InterfaceType.FullyQualifiedName,
			builder,
			indent,
			default
		);
		// Overwrite class start with manual attributes & class line for apples-to-apples benchmark
		// Remove the previously appended class start content by truncating back to namespace end.
		// Simpler: start a fresh builder section after header & namespace without using EmitClassStart.
		builder = new CodeWriter();
		builder.Write(EmbeddedResources.Instance.LoadEmbeddedResource("AutoGeneratedHeader"));
		indent = EmitHelpers.EmitNamespaceStart(
			target.ClassNamespace,
			target.ParentClasses,
			builder,
			default
		);
		builder
			.WriteIndent(indent)
			.WriteLine("[global::System.Runtime.CompilerServices.CompilerGenerated]")
			.WriteIndent(indent)
			.WriteLine(
				"[global::System.CodeDom.Compiler.GeneratedCode(\"Purview.Telemetry.SourceGenerator\", \"0.1.0.0\")]"
			)
			.WriteIndent(indent)
			.WriteLine(
				"[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
			)
			.WriteIndent(indent)
			.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]")
			.WriteIndent(indent)
			.Write("sealed partial class ")
			.Write(target.ClassNameToGenerate)
			.WriteLine()
			.WriteIndent(indent)
			.WriteLine("{");
		foreach (var method in target.Methods)
		{
			builder
				.WriteIndent(indent + 1)
				.Write("public void ")
				.Write(method.MethodName)
				.WriteLine("() {}");
		}
		builder.WriteIndent(indent).WriteLine("}");
		EmitHelpers.EmitNamespaceEnd(
			target.ClassNamespace,
			target.ParentClasses,
			indent,
			builder,
			default
		);
		EmitHelpers.EmitNamespaceEnd(
			target.ClassNamespace,
			target.ParentClasses,
			indent,
			builder,
			default
		);
		return builder.ToString();
	}
}
