namespace Purview.Telemetry;

/// <summary>
/// Naming convention strategies for generated telemetry names.
/// </summary>
{CodeGen}
enum NamingConvention
{
	/// <summary>
	/// Legacy naming (pre-v4): Lowercase ActivitySource names, smashed compound words, no word-boundary splitting.
	/// Use this to maintain compatibility with telemetry generated by older versions.
	/// </summary>
	Legacy = 0,

	/// <summary>
	/// OpenTelemetry-aligned naming (default from v4): Preserves casing for ActivitySource names,
	/// uses dot.separated.lowercase for metric instruments, snake_case for tags, follows OTel semantic conventions.
	/// Recommended for new projects and OpenTelemetry compatibility.
	/// </summary>
	OpenTelemetry = 1
}
