//HintName: Testing.MultiTelemetryCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class MultiTelemetryCore : global::Testing.IMultiTelemetry
	{
		global::System.Diagnostics.Metrics.Meter _meter = default!;

		global::System.Diagnostics.Metrics.Counter<int>? _incrementOperationCounterInstrument = null;
		global::System.Diagnostics.Metrics.Histogram<double>? _recordOperationDurationInstrument = null;
		global::System.Diagnostics.Metrics.UpDownCounter<int>? _updateActiveConnectionsInstrument = null;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		void InitializeMeters(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			if (_meter != null)
			{
				throw new global::System.Exception("The meters have already been initialized.");
			}

			global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

			global::System.Collections.Generic.Dictionary<string, object?> incrementOperationCounterTags = new();

			PopulateIncrementOperationCounterTags(incrementOperationCounterTags);

			_incrementOperationCounterInstrument = _meter.CreateCounter<int>(name: "multi.increment_operation_counter", unit: null, description: null, tags: incrementOperationCounterTags);
			global::System.Collections.Generic.Dictionary<string, object?> recordOperationDurationTags = new();

			PopulateRecordOperationDurationTags(recordOperationDurationTags);

			_recordOperationDurationInstrument = _meter.CreateHistogram<double>(name: "multi.record_operation_duration", unit: null, description: null, tags: recordOperationDurationTags);
			global::System.Collections.Generic.Dictionary<string, object?> updateActiveConnectionsTags = new();

			PopulateUpdateActiveConnectionsTags(updateActiveConnectionsTags);

			_updateActiveConnectionsInstrument = _meter.CreateUpDownCounter<int>(name: "multi.update_active_connections", unit: null, description: null, tags: updateActiveConnectionsTags);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateIncrementOperationCounterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateRecordOperationDurationTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateUpdateActiveConnectionsTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void IncrementOperationCounter(int value)
		{
			if (_incrementOperationCounterInstrument == null)
			{
				return;
			}

			_incrementOperationCounterInstrument.Add(value, tagList: default);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void RecordOperationDuration(double milliseconds)
		{
			if (_recordOperationDurationInstrument == null)
			{
				return;
			}

			_recordOperationDurationInstrument.Record(milliseconds, tagList: default);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void UpdateActiveConnections(int delta)
		{
			if (_updateActiveConnectionsInstrument == null)
			{
				return;
			}

			_updateActiveConnectionsInstrument.Add(delta, tagList: default);
		}
	}
}
