//HintName: Testing.TestLoggerCore.Logging.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class TestLoggerCore : global::Testing.ITestLogger
	{
		readonly global::Microsoft.Extensions.Logging.ILogger<global::Testing.ITestLogger> _logger;
		static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, int, global::System.Exception?> _hotPathV1LogEntryAction = global::Microsoft.Extensions.Logging.LoggerMessage.Define<int>(global::Microsoft.Extensions.Logging.LogLevel.Information, new global::Microsoft.Extensions.Logging.EventId(704618972, "HotPathV1LogEntry"), "HotPathV1LogEntry: Value = {Value}");

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestLoggerCore(global::Microsoft.Extensions.Logging.ILogger<global::Testing.ITestLogger> logger)
		{
			_logger = logger;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void RegularV2LogEntry(int value)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_logger.Log(
				global::Microsoft.Extensions.Logging.LogLevel.Information,
				new (164497939, nameof(RegularV2LogEntry)),
				new RegularV2LogEntry_LogState(value),
				null,
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
				static string (s, _) =>
				{
#if NET
					return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"RegularV2LogEntry: Value = {s._Value}");
#else
					return global::System.FormattableString.Invariant($"RegularV2LogEntry: Value = {s._Value}");
#endif
				}
			);

		}


		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void HotPathV1LogEntry(int value)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_hotPathV1LogEntryAction(_logger, value, null);
		}


	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	private readonly struct RegularV2LogEntry_LogState : global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.KeyValuePair<string, object?>>
	{
		static readonly string s_originalFormat = "RegularV2LogEntry: Value = {Value}";

		public readonly int _Value;

		public RegularV2LogEntry_LogState(int value)
		{
			_Value = value;
		}


		public int Count => 2;

		public global::System.Collections.Generic.KeyValuePair<string, object?> this[int index]
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
			get => index switch
			{
				0 => new("{OriginalFormat}", s_originalFormat),
				1 => new("value", _Value),
				_ => throw new global::System.IndexOutOfRangeException(nameof(index))
			};
		}


		public struct Enumerator : global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>>
		{
			readonly RegularV2LogEntry_LogState _state;
			int _index;

			public Enumerator(RegularV2LogEntry_LogState state)
			{
				_state = state;
				_index = -1;
			}

			public global::System.Collections.Generic.KeyValuePair<string, object?> Current => _state[_index];

			object? global::System.Collections.IEnumerator.Current => Current;

			public bool MoveNext() => ++_index < _state.Count;

			public void Reset() => _index = -1;

			public void Dispose() { }
		}


		public Enumerator GetEnumerator() => new(this);


		global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object?>>.GetEnumerator() => GetEnumerator();


		global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
	}

	}
}
