//HintName: Testing.MultiTelemetryCore.Logging.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class MultiTelemetryCore : global::Testing.IMultiTelemetry
	{
		readonly global::Microsoft.Extensions.Logging.ILogger<global::Testing.IMultiTelemetry> _logger;

		static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, string, int, double, global::System.Exception?> _logOperationAction = global::Microsoft.Extensions.Logging.LoggerMessage.Define<string, int, double>(global::Microsoft.Extensions.Logging.LogLevel.Information, new global::Microsoft.Extensions.Logging.EventId(1933755022, "LogOperation"), "LogOperation: OperationId = {OperationId}, Count = {Count}, Duration = {Duration}");
		static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, string, int, global::System.Exception?> _infoLogAction = global::Microsoft.Extensions.Logging.LoggerMessage.Define<string, int>(global::Microsoft.Extensions.Logging.LogLevel.Information, new global::Microsoft.Extensions.Logging.EventId(532711791, "InfoLog"), "InfoLog: Message = {Message}, UserId = {UserId}");

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public MultiTelemetryCore(global::Microsoft.Extensions.Logging.ILogger<global::Testing.IMultiTelemetry> logger, global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			_logger = logger;
			InitializeMeters(meterFactory);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void LogOperation(string operationId, int count, double duration)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_logOperationAction(_logger, operationId, count, duration, null);
		}


		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void InfoLog(string message, int userId)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_infoLogAction(_logger, message, userId, null);
		}

	}
}
