//HintName: Testing.MultiTelemetryCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class MultiTelemetryCore : global::Testing.IMultiTelemetry
	{
		global::System.Diagnostics.Metrics.Meter _meter = default!;

		global::System.Diagnostics.Metrics.Counter<int>? _incrementRequestCountInstrument = null;
		global::System.Diagnostics.Metrics.Histogram<double>? _recordRequestDurationInstrument = null;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		void InitializeMeters(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			if (_meter != null)
			{
				throw new global::System.Exception("The meters have already been initialized.");
			}

			global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

			global::System.Collections.Generic.Dictionary<string, object?> incrementRequestCountTags = new();

			PopulateIncrementRequestCountTags(incrementRequestCountTags);

			_incrementRequestCountInstrument = _meter.CreateCounter<int>(name: "testing-meter.increment_request_count", unit: null, description: null, tags: incrementRequestCountTags);
			global::System.Collections.Generic.Dictionary<string, object?> recordRequestDurationTags = new();

			PopulateRecordRequestDurationTags(recordRequestDurationTags);

			_recordRequestDurationInstrument = _meter.CreateHistogram<double>(name: "testing-meter.record_request_duration", unit: null, description: null, tags: recordRequestDurationTags);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateIncrementRequestCountTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateRecordRequestDurationTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void IncrementRequestCount(string endpoint)
		{
			if (_incrementRequestCountInstrument == null)
			{
				return;
			}

			_incrementRequestCountInstrument.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("endpoint", endpoint));
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void RecordRequestDuration(double milliseconds, string endpoint)
		{
			if (_recordRequestDurationInstrument == null)
			{
				return;
			}

			_recordRequestDurationInstrument.Record(milliseconds, new global::System.Collections.Generic.KeyValuePair<string, object?>("endpoint", endpoint));
		}
	}
}
