//HintName: MeterTelemetryCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
sealed partial class MeterTelemetryCore : global::IMeterTelemetry
{
	global::System.Diagnostics.Metrics.Meter _meter = default!;

	global::System.Diagnostics.Metrics.Counter<int>? _autoCounterMeterInstrument = null;
	global::System.Diagnostics.Metrics.Counter<int>? _autoIncrementMeterInstrument = null;
	global::System.Diagnostics.Metrics.Counter<int>? _counterMeterInstrument = null;
	global::System.Diagnostics.Metrics.Histogram<int>? _histogramMeterInstrument = null;
	global::System.Diagnostics.Metrics.ObservableCounter<float>? _observableCounterMeterInstrument = null;
	global::System.Diagnostics.Metrics.ObservableGauge<float>? _observableGaugeMeterInstrument = null;
	global::System.Diagnostics.Metrics.ObservableUpDownCounter<byte>? _observableUpDownCounterInstrument = null;
	global::System.Diagnostics.Metrics.UpDownCounter<decimal>? _upDownCounterMeterInstrument = null;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	public MeterTelemetryCore(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
	{
		InitializeMeters(meterFactory);
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	void InitializeMeters(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
	{
		if (_meter != null)
		{
			throw new global::System.Exception("The meters have already been initialized.");
		}

		global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

		PopulateMeterTags(meterTags);

		_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("Purview.Telemetry.SourceGenerator")
		{
			Version = null,
			Tags = meterTags
		});

		global::System.Collections.Generic.Dictionary<string, object?> autoCounterMeterTags = new();

		PopulateAutoCounterMeterTags(autoCounterMeterTags);

		_autoCounterMeterInstrument = _meter.CreateCounter<int>(name: "meter.auto_counter_meter", unit: null, description: null, tags: autoCounterMeterTags);
		global::System.Collections.Generic.Dictionary<string, object?> autoIncrementMeterTags = new();

		PopulateAutoIncrementMeterTags(autoIncrementMeterTags);

		_autoIncrementMeterInstrument = _meter.CreateCounter<int>(name: "meter.auto_increment_meter", unit: null, description: null, tags: autoIncrementMeterTags);
		global::System.Collections.Generic.Dictionary<string, object?> counterMeterTags = new();

		PopulateCounterMeterTags(counterMeterTags);

		_counterMeterInstrument = _meter.CreateCounter<int>(name: "meter.counter_meter", unit: null, description: null, tags: counterMeterTags);
		global::System.Collections.Generic.Dictionary<string, object?> histogramMeterTags = new();

		PopulateHistogramMeterTags(histogramMeterTags);

		_histogramMeterInstrument = _meter.CreateHistogram<int>(name: "meter.histogram_meter", unit: null, description: null, tags: histogramMeterTags);
		global::System.Collections.Generic.Dictionary<string, object?> upDownCounterMeterTags = new();

		PopulateUpDownCounterMeterTags(upDownCounterMeterTags);

		_upDownCounterMeterInstrument = _meter.CreateUpDownCounter<decimal>(name: "meter.up_down_counter_meter", unit: null, description: null, tags: upDownCounterMeterTags);
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateAutoCounterMeterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateAutoIncrementMeterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateCounterMeterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateHistogramMeterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateUpDownCounterMeterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void AutoCounterMeter(string someValue)
	{
		if (_autoCounterMeterInstrument == null)
		{
			return;
		}

		_autoCounterMeterInstrument.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("some_value", someValue));
	}
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void AutoIncrementMeter(string someValue)
	{
		if (_autoIncrementMeterInstrument == null)
		{
			return;
		}

		_autoIncrementMeterInstrument.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("some_value", someValue));
	}
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void CounterMeter(int measurement, float someValue)
	{
		if (_counterMeterInstrument == null)
		{
			return;
		}

		_counterMeterInstrument.Add(measurement, new global::System.Collections.Generic.KeyValuePair<string, object?>("some_value", someValue));
	}
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void HistogramMeter(int measurement, int someValue, bool anotherValue)
	{
		if (_histogramMeterInstrument == null)
		{
			return;
		}

		_histogramMeterInstrument.Record(measurement, new global::System.Collections.Generic.KeyValuePair<string, object?>("some_value", someValue), new global::System.Collections.Generic.KeyValuePair<string, object?>("another_value", anotherValue));
	}
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void ObservableCounterMeter(global::System.Func<float> measurement, double someValue)
	{
		if (_observableCounterMeterInstrument != null)
		{
			return;
		}

		_observableCounterMeterInstrument = _meter.CreateObservableCounter<float>("meter.observable_counter_meter", measurement, unit: null, description: null);
	}
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void ObservableGaugeMeter(global::System.Func<global::System.Diagnostics.Metrics.Measurement<float>> measurement, double someValue)
	{
		if (_observableGaugeMeterInstrument != null)
		{
			return;
		}

		_observableGaugeMeterInstrument = _meter.CreateObservableGauge<float>("meter.observable_gauge_meter", measurement, unit: null, description: null);
	}
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void ObservableUpDownCounter(global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.Diagnostics.Metrics.Measurement<byte>>> measurement, double someValue)
	{
		if (_observableUpDownCounterInstrument != null)
		{
			return;
		}

		_observableUpDownCounterInstrument = _meter.CreateObservableUpDownCounter<byte>("meter.observable_up_down_counter", measurement, unit: null, description: null);
	}
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void UpDownCounterMeter(decimal measurement, byte someValue)
	{
		if (_upDownCounterMeterInstrument == null)
		{
			return;
		}

		_upDownCounterMeterInstrument.Add(measurement, new global::System.Collections.Generic.KeyValuePair<string, object?>("some_value", someValue));
	}
}
