//HintName: Testing.TestLoggerCore.Logging.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class TestLoggerCore : global::Testing.ITestLogger
	{
		readonly global::Microsoft.Extensions.Logging.ILogger<global::Testing.ITestLogger> _logger;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestLoggerCore(global::Microsoft.Extensions.Logging.ILogger<global::Testing.ITestLogger> logger)
		{
			_logger = logger;
		}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	private readonly struct HotPathV1LogEntry_LogState : global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.KeyValuePair<string, object?>>
	{
		static readonly string s_originalFormat = "HotPathV1LogEntry: A = {A}, B = {B}, C = {C}, D = {D}, E = {E}, F = {F}, G = {G}";

		public readonly int _A;
		public readonly int _B;
		public readonly int _C;
		public readonly int _D;
		public readonly int _E;
		public readonly int _F;
		public readonly int _G;

		public HotPathV1LogEntry_LogState(int a, int b, int c, int d, int e, int f, int g)
		{
			_A = a;
			_B = b;
			_C = c;
			_D = d;
			_E = e;
			_F = f;
			_G = g;
		}


		public int Count => 8;

		public global::System.Collections.Generic.KeyValuePair<string, object?> this[int index]
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
			get => index switch
			{
				0 => new("{OriginalFormat}", s_originalFormat),
				1 => new("a", _A),
				2 => new("b", _B),
				3 => new("c", _C),
				4 => new("d", _D),
				5 => new("e", _E),
				6 => new("f", _F),
				7 => new("g", _G),
				_ => throw new global::System.IndexOutOfRangeException(nameof(index))
			};
		}


		public struct Enumerator : global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>>
		{
			readonly HotPathV1LogEntry_LogState _state;
			int _index;

			public Enumerator(HotPathV1LogEntry_LogState state)
			{
				_state = state;
				_index = -1;
			}

			public global::System.Collections.Generic.KeyValuePair<string, object?> Current => _state[_index];

			object? global::System.Collections.IEnumerator.Current => Current;

			public bool MoveNext() => ++_index < _state.Count;

			public void Reset() => _index = -1;

			public void Dispose() { }
		}


		public Enumerator GetEnumerator() => new(this);


		global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object?>>.GetEnumerator() => GetEnumerator();


		global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
	}

	}
}
