//HintName: NamingConvention.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#if !NET48_OR_GREATER && !PURVIEW_TELEMETRY_NON_NULLABLE
#nullable enable
#endif

namespace Purview.Telemetry
{

/// <summary>
/// Naming convention strategies for generated telemetry names.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::Microsoft.CodeAnalysis.Embedded]
enum NamingConvention
{
	/// <summary>
	/// Legacy naming (pre-v4): Lowercase ActivitySource names, smashed compound words, no word-boundary splitting.
	/// Use this to maintain compatibility with telemetry generated by older versions.
	/// </summary>
	Legacy = 0,

	/// <summary>
	/// OpenTelemetry-aligned naming (default from v4): Preserves casing for ActivitySource names,
	/// uses dot.separated.lowercase for metric instruments, snake_case for tags, follows OTel semantic conventions.
	/// Recommended for new projects and OpenTelemetry compatibility.
	/// </summary>
	OpenTelemetry = 1
}
}
