//HintName: Testing.MultiTelemetryCore.Logging.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class MultiTelemetryCore : global::Testing.IMultiTelemetry
	{
		readonly global::Microsoft.Extensions.Logging.ILogger<global::Testing.IMultiTelemetry> _logger;
		static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, string, int, global::System.DateTime, string?, global::System.Exception?> _logProcessingAction = global::Microsoft.Extensions.Logging.LoggerMessage.Define<string, int, global::System.DateTime, string?>(global::Microsoft.Extensions.Logging.LogLevel.Information, new global::Microsoft.Extensions.Logging.EventId(1197388818, "LogProcessing"), "LogProcessing: RequestId = {RequestId}, UserId = {UserId}, Timestamp = {Timestamp}, CorrelationId = {CorrelationId}");

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public MultiTelemetryCore(global::Microsoft.Extensions.Logging.ILogger<global::Testing.IMultiTelemetry> logger, global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			_logger = logger;
			InitializeMeters(meterFactory);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void LogProcessing(string requestId, int userId, global::System.DateTime timestamp, string? correlationId)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_logProcessingAction(_logger, requestId, userId, timestamp, correlationId, null);
		}

	}
}
