//HintName: Test.Complex.OrderServiceCore.MultiTarget.g.cs
// <auto-generated>
//	This code was generated by the Purview.Telemetry.SourceGenerator
//	on {Scrubbed}.
//
//	Changes to this file may cause incorrect behaviour and will be lost
//	when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Test.Complex
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	sealed partial class OrderServiceCore : Test.Complex.IOrderService
	{
		readonly global::System.Diagnostics.ActivitySource _activitySource;
		readonly global::Microsoft.Extensions.Logging.ILogger _logger;
		readonly global::System.Diagnostics.Metrics.Meter _meter;

		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public OrderServiceCore(global::System.Diagnostics.ActivitySource activitySource, global::Microsoft.Extensions.Logging.ILogger logger, global::System.Diagnostics.Metrics.Meter meter)
		{
			_activitySource = activitySource;
			_logger = logger;
			_meter = meter;
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public Task<bool> ProcessOrderAsync(string orderId, int customerId, string correlationId, System.DateTime timestamp, string internalToken)
		{
			using var activity = _activitySource.StartActivity("ProcessOrderAsync");
			activity?.SetTag("order.id", orderId);
			activity?.SetTag("customer.id", customerId);
			activity?.SetBaggage("correlation.id", correlationId?.ToString());

			_logger.LogInformation("ProcessOrderAsync called, {orderId}, {customerId}, {correlationId}, {timestamp}", orderId, customerId, correlationId, timestamp);

			// Metrics instrumentation for ProcessOrderAsync
			var tags = global::System.Array.Empty<global::System.Collections.Generic.KeyValuePair<string, object?>>();
			// TODO: Replace with appropriate metric instrument call based on method configuration

			// Example: _someCounter.Add(1, tags);


			return default;
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void CancelOrder(string orderId, string reason)
		{
			using var activity = _activitySource.StartActivity("CancelOrder");
			activity?.SetTag("orderId", orderId);

			_logger.LogInformation("CancelOrder called, {orderId}, {reason}", orderId, reason);

		}

		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void IncrementOrderCount(string orderType, int count)
		{
			// Metrics instrumentation for IncrementOrderCount
			var tags = global::System.Array.Empty<global::System.Collections.Generic.KeyValuePair<string, object?>>();
			// TODO: Replace with appropriate metric instrument call based on method configuration

			// Example: _someCounter.Add(1, tags);


		}

	}
}