//HintName: Testing.InvalidTelemetryCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class InvalidTelemetryCore : global::Testing.IInvalidTelemetry
	{
		readonly global::System.Diagnostics.Metrics.Meter _meter;

		readonly global::System.Diagnostics.Metrics.Counter<int> _invalidAutoCounterReturnInstrument;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public InvalidTelemetryCore(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			global::System.Collections.Generic.Dictionary<string, object?> meterTags = new global::System.Collections.Generic.Dictionary<string, object?>();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

			global::System.Collections.Generic.Dictionary<string, object?> invalidAutoCounterReturnTags = new global::System.Collections.Generic.Dictionary<string, object?>();

			PopulateInvalidAutoCounterReturnTags(invalidAutoCounterReturnTags);

			_invalidAutoCounterReturnInstrument = _meter.CreateCounter<int>(name: "invalid.invalid_auto_counter_return", unit: null, description: null, tags: invalidAutoCounterReturnTags);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateInvalidAutoCounterReturnTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	}
}
