//HintName: Testing.TestMetricsCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class TestMetricsCore : global::Testing.ITestMetrics
	{
		readonly global::System.Diagnostics.Metrics.Meter _meter;

		readonly global::System.Diagnostics.Metrics.Counter<int> _autoCounterInstrument;
		readonly global::System.Diagnostics.Metrics.Counter<int> _counter_AutoIncrementInstrument;
		readonly global::System.Diagnostics.Metrics.Counter<int> _counterInstrument;
		readonly global::System.Diagnostics.Metrics.Histogram<int> _histogramInstrument;
		readonly global::System.Diagnostics.Metrics.UpDownCounter<int> _upDownCounterInstrument;
		global::System.Diagnostics.Metrics.ObservableCounter<int> _observableCounterInstrument = default!;
		global::System.Diagnostics.Metrics.ObservableGauge<int> _observableGaugeInstrument = default!;
		global::System.Diagnostics.Metrics.ObservableUpDownCounter<int> _observableUpDownCounterInstrument = default!;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestMetricsCore(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

			global::System.Collections.Generic.Dictionary<string, object?> autoCounterTags = new();

			PopulateAutoCounterTags(autoCounterTags);

			_autoCounterInstrument = _meter.CreateCounter<int>(name: "test_metrics.auto_counter", unit: null, description: null, tags: autoCounterTags);
			global::System.Collections.Generic.Dictionary<string, object?> counter_AutoIncrementTags = new();

			PopulateCounter_AutoIncrementTags(counter_AutoIncrementTags);

			_counter_AutoIncrementInstrument = _meter.CreateCounter<int>(name: "test_metrics.counter_auto_increment", unit: null, description: null, tags: counter_AutoIncrementTags);
			global::System.Collections.Generic.Dictionary<string, object?> counterTags = new();

			PopulateCounterTags(counterTags);

			_counterInstrument = _meter.CreateCounter<int>(name: "test_metrics.counter", unit: null, description: null, tags: counterTags);
			global::System.Collections.Generic.Dictionary<string, object?> histogramTags = new();

			PopulateHistogramTags(histogramTags);

			_histogramInstrument = _meter.CreateHistogram<int>(name: "test_metrics.histogram", unit: null, description: null, tags: histogramTags);
			global::System.Collections.Generic.Dictionary<string, object?> upDownCounterTags = new();

			PopulateUpDownCounterTags(upDownCounterTags);

			_upDownCounterInstrument = _meter.CreateUpDownCounter<int>(name: "test_metrics.up_down_counter", unit: null, description: null, tags: upDownCounterTags);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateAutoCounterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateCounter_AutoIncrementTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateCounterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateHistogramTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateUpDownCounterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void AutoCounter(global::System.Collections.Generic.IEnumerable<string> genericParameter)
		{
			_autoCounterInstrument.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("generic_parameter", genericParameter));
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Counter_AutoIncrement(global::System.Collections.Generic.IEnumerable<string> genericParameter)
		{
			_counter_AutoIncrementInstrument.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("generic_parameter", genericParameter));
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Counter(int value, global::System.Collections.Generic.IEnumerable<string> genericParameter)
		{
			_counterInstrument.Add(value, new global::System.Collections.Generic.KeyValuePair<string, object?>("generic_parameter", genericParameter));
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Histogram(int value, global::System.Collections.Generic.IEnumerable<string> genericParameter)
		{
			_histogramInstrument.Record(value, new global::System.Collections.Generic.KeyValuePair<string, object?>("generic_parameter", genericParameter));
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void UpDownCounter(int value, global::System.Collections.Generic.IEnumerable<string> genericParameter)
		{
			_upDownCounterInstrument.Add(value, new global::System.Collections.Generic.KeyValuePair<string, object?>("generic_parameter", genericParameter));
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableCounter(global::System.Func<int> valueFunc, global::System.Collections.Generic.IEnumerable<string> genericParameter)
		{
			if (_observableCounterInstrument != null)
			{
				return;
			}

			_observableCounterInstrument = _meter.CreateObservableCounter<int>("test_metrics.observable_counter", valueFunc, unit: null, description: null);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableGauge(global::System.Func<int> valueFunc, global::System.Collections.Generic.IEnumerable<string> genericParameter)
		{
			if (_observableGaugeInstrument != null)
			{
				return;
			}

			_observableGaugeInstrument = _meter.CreateObservableGauge<int>("test_metrics.observable_gauge", valueFunc, unit: null, description: null);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableUpDownCounter(global::System.Func<int> valueFunc, global::System.Collections.Generic.IEnumerable<string> genericParameter)
		{
			if (_observableUpDownCounterInstrument != null)
			{
				return;
			}

			_observableUpDownCounterInstrument = _meter.CreateObservableUpDownCounter<int>("test_metrics.observable_up_down_counter", valueFunc, unit: null, description: null);
		}
	}
}
