//HintName: Test.TestServiceImplementation.MultiTarget.g.cs
// <auto-generated>
//	This code was generated by the Purview.Telemetry.SourceGenerator
//	on {Scrubbed}.
//
//	Changes to this file may cause incorrect behaviour and will be lost
//	when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Test;

partial class TestServiceImplementation : ITestService
{
	readonly global::System.Diagnostics.ActivitySource _activitySource;
	readonly global::Microsoft.Extensions.Logging.ILogger _logger;

	public TestServiceImplementation(global::System.Diagnostics.ActivitySource activitySource, global::Microsoft.Extensions.Logging.ILogger logger)
	{
		_activitySource = activitySource;
		_logger = logger;
	}

	public void TestOperation(string userId, int count)
	{
		TestOperation_Activity(userId, count);
		TestOperation_Logging(userId, count);
	}

	private void TestOperation_Activity(string userId, int count)
	{
		// Activity telemetry generation
		// TODO: Implement activity generation logic
	}

	private void TestOperation_Logging(string userId, int count)
	{
		// Logging telemetry generation
		// TODO: Implement logging generation logic
	}

}
