//HintName: Testing.TestMetricsCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class TestMetricsCore : global::Testing.ITestMetrics
	{
		global::System.Diagnostics.Metrics.Meter _meter = default!;

		global::System.Diagnostics.Metrics.ObservableCounter<int>? _counterInstrument = null;
		global::System.Diagnostics.Metrics.ObservableGauge<int>? _gaugeInstrument = null;
		global::System.Diagnostics.Metrics.ObservableUpDownCounter<int>? _upDownInstrument = null;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestMetricsCore(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			InitializeMeters(meterFactory);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		void InitializeMeters(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			if (_meter != null)
			{
				throw new global::System.Exception("The meters have already been initialized.");
			}

			global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Counter(global::System.Func<int> counterValue, int intParam, bool boolParam)
		{
			if (_counterInstrument != null)
			{
				throw new global::System.Exception("testing-meter.counter has already been initialized.");
			}

			global::System.Diagnostics.TagList counterTagList = new();

			counterTagList.Add("int_param", intParam);
			counterTagList.Add("bool_param", boolParam);

			_counterInstrument = _meter.CreateObservableCounter<int>("testing-meter.counter", counterValue, unit: null, description: null
				, tags: counterTagList
			);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Gauge(global::System.Func<int> gaugeValue, int intParam, bool boolParam)
		{
			if (_gaugeInstrument != null)
			{
				throw new global::System.Exception("testing-meter.gauge has already been initialized.");
			}

			global::System.Diagnostics.TagList gaugeTagList = new();

			gaugeTagList.Add("int_param", intParam);
			gaugeTagList.Add("bool_param", boolParam);

			_gaugeInstrument = _meter.CreateObservableGauge<int>("testing-meter.gauge", gaugeValue, unit: null, description: null
				, tags: gaugeTagList
			);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void UpDown(global::System.Func<int> upDownValue, int intParam, bool boolParam)
		{
			if (_upDownInstrument != null)
			{
				throw new global::System.Exception("testing-meter.up.down has already been initialized.");
			}

			global::System.Diagnostics.TagList upDownTagList = new();

			upDownTagList.Add("int_param", intParam);
			upDownTagList.Add("bool_param", boolParam);

			_upDownInstrument = _meter.CreateObservableUpDownCounter<int>("testing-meter.up.down", upDownValue, unit: null, description: null
				, tags: upDownTagList
			);
		}
	}
}
