//HintName: Test.TestServiceImplementation.MultiTarget.g.cs
// <auto-generated>
//	This code was generated by the Purview.Telemetry.SourceGenerator
//	on {Scrubbed}.
//
//	Changes to this file may cause incorrect behaviour and will be lost
//	when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Test;

partial class TestServiceImplementation : ITestService
{
	readonly global::System.Diagnostics.ActivitySource _activitySource;
	readonly global::Microsoft.Extensions.Logging.ILogger _logger;
	readonly global::System.Diagnostics.Metrics.Meter _meter;

	public TestServiceImplementation(global::System.Diagnostics.ActivitySource activitySource, global::Microsoft.Extensions.Logging.ILogger logger, global::System.Diagnostics.Metrics.Meter meter)
	{
		_activitySource = activitySource;
		_logger = logger;
		_meter = meter;
	}

	public void TestOperation(string userId, string internalId, int sensitiveCount, System.DateTime timestamp)
	{
		TestOperation_Activity(userId, sensitiveCount, timestamp);
		TestOperation_Logging(userId, internalId, timestamp);
		TestOperation_Metrics(userId, internalId, sensitiveCount);
	}

	private void TestOperation_Activity(string userId, int sensitiveCount, System.DateTime timestamp)
	{
		// Activity telemetry generation
		// TODO: Implement activity generation logic
	}

	private void TestOperation_Logging(string userId, string internalId, System.DateTime timestamp)
	{
		// Logging telemetry generation
		// TODO: Implement logging generation logic
	}

	private void TestOperation_Metrics(string userId, string internalId, int sensitiveCount)
	{
		// Metrics telemetry generation
		// TODO: Implement metrics generation logic
	}

}
