//HintName: Testing.TestLoggerCore.Logging.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class TestLoggerCore : global::Testing.ITestLogger
	{
		readonly global::Microsoft.Extensions.Logging.ILogger<global::Testing.ITestLogger> _logger;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestLoggerCore(global::Microsoft.Extensions.Logging.ILogger<global::Testing.ITestLogger> logger)
		{
			_logger = logger;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void LogEntryWithMoreThanSixParams(int one, int two, int three, int four, int five, int six, int seven, int eight, int nine, int ten, int eleven)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_logger.Log(
				global::Microsoft.Extensions.Logging.LogLevel.Information,
				new (282537637, nameof(LogEntryWithMoreThanSixParams)),
				new LogEntryWithMoreThanSixParams_LogState(one, two, three, four, five, six, seven, eight, nine, ten, eleven),
				null,
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
				static string (s, _) =>
				{
#if NET
					return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"LogEntryWithMoreThanSixParams: One = {s._One}, Two = {s._Two}, Three = {s._Three}, Four = {s._Four}, Five = {s._Five}, Six = {s._Six}, Seven = {s._Seven}, Eight = {s._Eight}, Nine = {s._Nine}, Ten = {s._Ten}, Eleven = {s._Eleven}");
#else
					return global::System.FormattableString.Invariant($"LogEntryWithMoreThanSixParams: One = {s._One}, Two = {s._Two}, Three = {s._Three}, Four = {s._Four}, Five = {s._Five}, Six = {s._Six}, Seven = {s._Seven}, Eight = {s._Eight}, Nine = {s._Nine}, Ten = {s._Ten}, Eleven = {s._Eleven}");
#endif
				}
			);

		}


	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	private readonly struct LogEntryWithMoreThanSixParams_LogState : global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.KeyValuePair<string, object?>>
	{
		static readonly string s_originalFormat = "LogEntryWithMoreThanSixParams: One = {One}, Two = {Two}, Three = {Three}, Four = {Four}, Five = {Five}, Six = {Six}, Seven = {Seven}, Eight = {Eight}, Nine = {Nine}, Ten = {Ten}, Eleven = {Eleven}";

		public readonly int _One;
		public readonly int _Two;
		public readonly int _Three;
		public readonly int _Four;
		public readonly int _Five;
		public readonly int _Six;
		public readonly int _Seven;
		public readonly int _Eight;
		public readonly int _Nine;
		public readonly int _Ten;
		public readonly int _Eleven;

		public LogEntryWithMoreThanSixParams_LogState(int one, int two, int three, int four, int five, int six, int seven, int eight, int nine, int ten, int eleven)
		{
			_One = one;
			_Two = two;
			_Three = three;
			_Four = four;
			_Five = five;
			_Six = six;
			_Seven = seven;
			_Eight = eight;
			_Nine = nine;
			_Ten = ten;
			_Eleven = eleven;
		}


		public int Count => 12;

		public global::System.Collections.Generic.KeyValuePair<string, object?> this[int index]
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
			get => index switch
			{
				0 => new("{OriginalFormat}", s_originalFormat),
				1 => new("one", _One),
				2 => new("two", _Two),
				3 => new("three", _Three),
				4 => new("four", _Four),
				5 => new("five", _Five),
				6 => new("six", _Six),
				7 => new("seven", _Seven),
				8 => new("eight", _Eight),
				9 => new("nine", _Nine),
				10 => new("ten", _Ten),
				11 => new("eleven", _Eleven),
				_ => throw new global::System.IndexOutOfRangeException(nameof(index))
			};
		}


		public struct Enumerator : global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>>
		{
			readonly LogEntryWithMoreThanSixParams_LogState _state;
			int _index;

			public Enumerator(LogEntryWithMoreThanSixParams_LogState state)
			{
				_state = state;
				_index = -1;
			}

			public global::System.Collections.Generic.KeyValuePair<string, object?> Current => _state[_index];

			object? global::System.Collections.IEnumerator.Current => Current;

			public bool MoveNext() => ++_index < _state.Count;

			public void Reset() => _index = -1;

			public void Dispose() { }
		}


		public Enumerator GetEnumerator() => new(this);


		global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object?>>.GetEnumerator() => GetEnumerator();


		global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
	}

	}
}
