//HintName: Test.TestServiceCore.MultiTarget.g.cs
// <auto-generated>
//	This code was generated by the Purview.Telemetry.SourceGenerator
//	on {Scrubbed}.
//
//	Changes to this file may cause incorrect behaviour and will be lost
//	when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Test
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	sealed partial class TestServiceCore : Test.ITestService
	{
		readonly global::System.Diagnostics.ActivitySource _activitySource;
		readonly global::Microsoft.Extensions.Logging.ILogger _logger;

		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestServiceCore(global::System.Diagnostics.ActivitySource activitySource, global::Microsoft.Extensions.Logging.ILogger logger)
		{
			_activitySource = activitySource;
			_logger = logger;
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void TestOperation(string userId, string context, int count)
		{
			using var activity = _activitySource.StartActivity("TestOperation");
			activity?.SetTag("user_id", userId);
			activity?.SetBaggage("operation_context", context?.ToString());

			_logger.LogInformation("TestOperation called, {userId}, {context}, {count}", userId, context, count);

		}

	}
}