//HintName: MeterNameGenerationType.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#if !NET48_OR_GREATER && !PURVIEW_TELEMETRY_NON_NULLABLE
#nullable enable
#endif

namespace Purview.Telemetry
{

/// <summary>
/// Determines how meter names are generated when not explicitly specified.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::Microsoft.CodeAnalysis.Embedded]
enum MeterNameGenerationType
{
	/// <summary>
	/// OpenTelemetry convention: Assembly name lowercased with dots separating namespaces.
	/// Example: "MyCompany.MyApp" becomes "mycompany.myapp".
	/// Follows OpenTelemetry semantic conventions for meter naming.
	/// </summary>
	OpenTelemetry = 0,

	/// <summary>
	/// .NET convention (default): Assembly name preserved as-is without case transformation.
	/// Example: "MyCompany.MyApp" remains "MyCompany.MyApp".
	/// </summary>
	DotNet = 1
}
}
