//HintName: TestTelemetryCore.Activity.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
sealed partial class TestTelemetryCore : global::ITestTelemetry
{
	readonly static global::System.Diagnostics.ActivitySource _activitySource = new global::System.Diagnostics.ActivitySource("activity-source");

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	static void RecordExceptionInternal(global::System.Diagnostics.Activity? activity, global::System.Exception? exception, bool escape)
	{
		if (activity == null || exception == null)
		{
			return;
		}

		global::System.Diagnostics.ActivityTagsCollection tagsCollection = new global::System.Diagnostics.ActivityTagsCollection();
		tagsCollection.Add("exception.escaped", escape);
		tagsCollection.Add("exception.message", exception.Message);
		tagsCollection.Add("exception.type", exception.GetType().FullName);
		tagsCollection.Add("exception.stacktrace", exception.StackTrace);

		global::System.Diagnostics.ActivityEvent recordExceptionEvent = new global::System.Diagnostics.ActivityEvent(name: "exception", timestamp: default, tags: tagsCollection);

		activity.AddEvent(recordExceptionEvent);
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public global::System.Diagnostics.Activity? DuplicateMethodName(string stringParam, int intParam, bool boolParam)
	{
		if (!_activitySource.HasListeners())
		{
			return null;
		}

		global::System.Diagnostics.Activity? activityDuplicateMethodName = _activitySource.StartActivity("DuplicateMethodName", global::System.Diagnostics.ActivityKind.Internal, parentId: default, tags: default, links: default, startTime: default);

		if (activityDuplicateMethodName != null)
		{
			activityDuplicateMethodName.SetTag("int_param", intParam);
			activityDuplicateMethodName.SetTag("bool_param", boolParam);
			activityDuplicateMethodName.SetBaggage("string_param", stringParam);
		}

		return activityDuplicateMethodName;
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void DuplicateMethodName(global::System.Diagnostics.Activity? activity, string stringParam)
	{
		if (!_activitySource.HasListeners())
		{
			return;
		}

		if (activity != null)
		{
			global::System.Diagnostics.ActivityTagsCollection tagsCollectionDuplicateMethodName = new();
			tagsCollectionDuplicateMethodName.Add("string_param", stringParam);

			global::System.Diagnostics.ActivityEvent activityEventDuplicateMethodName = new global::System.Diagnostics.ActivityEvent(name: "DuplicateMethodName", timestamp: default, tags: tagsCollectionDuplicateMethodName);

			activity.AddEvent(activityEventDuplicateMethodName);
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void DuplicateMethodName(global::System.Diagnostics.Activity? activity, int intParam)
	{
		if (!_activitySource.HasListeners())
		{
			return;
		}

		if (activity != null)
		{
			activity.SetTag("int_param", intParam);
		}
	}

}
