//HintName: TestTelemetryCore.Logging.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
sealed partial class TestTelemetryCore : global::ITestTelemetry
{
	readonly global::Microsoft.Extensions.Logging.ILogger<global::ITestTelemetry> _logger;
	static readonly global::System.Func<global::Microsoft.Extensions.Logging.ILogger, string, int, bool, global::System.IDisposable?> _duplicateMethodNameAction = global::Microsoft.Extensions.Logging.LoggerMessage.DefineScope<string, int, bool>("DuplicateMethodName: StringParam = {StringParam}, IntParam = {IntParam}, BoolParam = {BoolParam}");

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	public TestTelemetryCore(global::Microsoft.Extensions.Logging.ILogger<global::ITestTelemetry> logger)
	{
		_logger = logger;
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public global::System.IDisposable? DuplicateMethodName(string stringParam, int intParam, bool boolParam)
	{
		return _duplicateMethodNameAction(_logger, stringParam, intParam, boolParam);
	}


	public void DuplicateMethodName() => throw new global::System.NotSupportedException();

}
