//HintName: TestTelemetryCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
sealed partial class TestTelemetryCore : global::ITestTelemetry
{
	readonly global::System.Diagnostics.Metrics.Meter _meter;

	readonly global::System.Diagnostics.Metrics.Counter<int> _duplicateMethodNameInstrument;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	public TestTelemetryCore(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
	{
		global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

		PopulateMeterTags(meterTags);

		_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("Purview.Telemetry.SourceGenerator")
		{
			Version = null,
			Tags = meterTags
		});

		global::System.Collections.Generic.Dictionary<string, object?> duplicateMethodNameTags = new();

		PopulateDuplicateMethodNameTags(duplicateMethodNameTags);

		_duplicateMethodNameInstrument = _meter.CreateCounter<int>(name: "test.duplicate_method_name", unit: null, description: null, tags: duplicateMethodNameTags);
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateDuplicateMethodNameTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void DuplicateMethodName(string stringParam, int intParam, bool boolParam)
	{
		_duplicateMethodNameInstrument.Add(1, new global::System.Collections.Generic.KeyValuePair<string, object?>("string_param", stringParam), new global::System.Collections.Generic.KeyValuePair<string, object?>("int_param", intParam), new global::System.Collections.Generic.KeyValuePair<string, object?>("bool_param", boolParam));
	}

	public void DuplicateMethodName(int measurementValue) => throw new global::System.NotSupportedException();

}
