//HintName: ExcludeTargetsAttribute.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#if !NET48_OR_GREATER && !PURVIEW_TELEMETRY_NON_NULLABLE
#nullable enable
#endif

namespace Purview.Telemetry
{

/// <summary>
/// Excludes a parameter from specific telemetry generation targets.
/// Use this attribute when a method has multiple generation targets (Activity + Log + Metric)
/// and certain parameters should not be included in specific targets.
/// </summary>
/// <example>
/// <code>
/// [Activity]
/// [Info]
/// [Counter]
/// Activity? CacheHit(
///     string cacheName,
///     [ExcludeTargets(Targets.Metrics)] string message,  // Excluded from metrics
///     [InstrumentMeasurement] int count
/// );
/// </code>
/// </example>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("PURVIEW_TELEMETRY_ATTRIBUTES")]
sealed class ExcludeTargetsAttribute : global::System.Attribute
{
	/// <summary>
	/// Creates a new instance of <see cref="ExcludeTargetsAttribute"/> with the specified targets to exclude.
	/// </summary>
	/// <param name="targets">The generation targets to exclude this parameter from.</param>
	public ExcludeTargetsAttribute(global::Purview.Telemetry.Targets targets)
	{
		ExcludedTargets = targets;
	}

	/// <summary>
	/// Gets the targets this parameter should be excluded from.
	/// </summary>
	public global::Purview.Telemetry.Targets ExcludedTargets { get; }
}
}
