//HintName: Testing.MultiTelemetryCore.Activity.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class MultiTelemetryCore : global::Testing.IMultiTelemetry
	{
		readonly static global::System.Diagnostics.ActivitySource _activitySource = new("testing-activity-source");

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		static void RecordExceptionInternal(global::System.Diagnostics.Activity? activity, global::System.Exception? exception, bool escape)
		{
			if (activity == null || exception == null)
			{
				return;
			}

			global::System.Diagnostics.ActivityTagsCollection tagsCollection = new();
			tagsCollection.Add("exception.escaped", escape);
			tagsCollection.Add("exception.message", exception.Message);
			tagsCollection.Add("exception.type", exception.GetType().FullName);
			tagsCollection.Add("exception.stacktrace", exception.StackTrace);

			global::System.Diagnostics.ActivityEvent recordExceptionEvent = new(name: "exception", timestamp: default, tags: tagsCollection);

			activity.AddEvent(recordExceptionEvent);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public global::System.Diagnostics.Activity? StartOperation(string operationId)
		{
			if (!_activitySource.HasListeners())
			{
				return null;
			}

			global::System.Diagnostics.Activity? activityStartOperation = _activitySource.StartActivity("StartOperation", global::System.Diagnostics.ActivityKind.Internal, parentId: default, tags: default, links: default, startTime: default);

			if (activityStartOperation != null)
			{
				activityStartOperation.SetTag("operation_id", operationId);
			}

			return activityStartOperation;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void SetContext(global::System.Diagnostics.Activity? activity, string key, string value)
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (activity != null)
			{
				activity.SetTag("key", key);
				activity.SetTag("value", value);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void RecordEvent(global::System.Diagnostics.Activity? activity, string eventName)
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (activity != null)
			{
				global::System.Diagnostics.ActivityTagsCollection tagsCollectionRecordEvent = new();
				tagsCollectionRecordEvent.Add("event_name", eventName);

				global::System.Diagnostics.ActivityEvent activityEventRecordEvent = new(name: "RecordEvent", timestamp: default, tags: tagsCollectionRecordEvent);

				activity.AddEvent(activityEventRecordEvent);
			}
		}

	}
}
