//HintName: Testing.TestMetricsCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class TestMetricsCore : global::Testing.ITestMetrics
	{
		global::System.Diagnostics.Metrics.Meter _meter = default!;

		global::System.Diagnostics.Metrics.ObservableGauge<int>? _observableGaugeInstrument = null;
		global::System.Diagnostics.Metrics.ObservableGauge<int>? _observableGauge2Instrument = null;
		global::System.Diagnostics.Metrics.ObservableGauge<int>? _observableGauge3Instrument = null;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestMetricsCore(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			InitializeMeters(meterFactory);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		void InitializeMeters(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			if (_meter != null)
			{
				throw new global::System.Exception("The meters have already been initialized.");
			}

			global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableGauge(global::System.Func<int> f, int intParam, bool boolParam)
		{
			if (_observableGaugeInstrument != null)
			{
				return;
			}

			global::System.Diagnostics.TagList observableGaugeTagList = new();

			observableGaugeTagList.Add("int_param", intParam);
			observableGaugeTagList.Add("bool_param", boolParam);

			_observableGaugeInstrument = _meter.CreateObservableGauge<int>("testing-meter.observable_gauge", f, unit: null, description: null
				, tags: observableGaugeTagList
			);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableGauge2(global::System.Func<global::System.Diagnostics.Metrics.Measurement<int>> f, int intParam, bool boolParam)
		{
			if (_observableGauge2Instrument != null)
			{
				throw new global::System.Exception("testing-meter.observable_gauge2 has already been initialized.");
			}

			global::System.Diagnostics.TagList observableGauge2TagList = new();

			observableGauge2TagList.Add("int_param", intParam);
			observableGauge2TagList.Add("bool_param", boolParam);

			_observableGauge2Instrument = _meter.CreateObservableGauge<int>("testing-meter.observable_gauge2", f, unit: null, description: null
				, tags: observableGauge2TagList
			);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableGauge3(global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.Diagnostics.Metrics.Measurement<int>>> f, int intParam, bool boolParam)
		{
			if (_observableGauge3Instrument != null)
			{
				return;
			}

			global::System.Diagnostics.TagList observableGauge3TagList = new();

			observableGauge3TagList.Add("int_param", intParam);
			observableGauge3TagList.Add("bool_param", boolParam);

			_observableGauge3Instrument = _meter.CreateObservableGauge<int>("testing-meter.observable_gauge3", f, unit: null, description: null
				, tags: observableGauge3TagList
			);
		}
	}
}
