//HintName: Testing.MultiTelemetryCore.Metric.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class MultiTelemetryCore : global::Testing.IMultiTelemetry
	{
		global::System.Diagnostics.Metrics.Meter _meter = default!;

		global::System.Diagnostics.Metrics.Counter<int>? _incrementCounterInstrument = null;
		global::System.Diagnostics.Metrics.Counter<int>? _autoIncrementInstrument = null;
		global::System.Diagnostics.Metrics.UpDownCounter<int>? _updateUpDownCounterInstrument = null;
		global::System.Diagnostics.Metrics.Histogram<double>? _recordHistogramInstrument = null;
		global::System.Diagnostics.Metrics.ObservableCounter<long>? _getObservableCounterInstrument = null;
		global::System.Diagnostics.Metrics.ObservableGauge<double>? _getObservableGaugeInstrument = null;
		global::System.Diagnostics.Metrics.ObservableUpDownCounter<int>? _getObservableUpDownCounterInstrument = null;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public MultiTelemetryCore(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			InitializeMeters(meterFactory);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		void InitializeMeters(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			if (_meter != null)
			{
				throw new global::System.Exception("The meters have already been initialized.");
			}

			global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

			global::System.Collections.Generic.Dictionary<string, object?> incrementCounterTags = new();

			PopulateIncrementCounterTags(incrementCounterTags);

			_incrementCounterInstrument = _meter.CreateCounter<int>(name: "multi.increment_counter", unit: null, description: null, tags: incrementCounterTags);
			global::System.Collections.Generic.Dictionary<string, object?> autoIncrementTags = new();

			PopulateAutoIncrementTags(autoIncrementTags);

			_autoIncrementInstrument = _meter.CreateCounter<int>(name: "multi.auto_increment", unit: null, description: null, tags: autoIncrementTags);
			global::System.Collections.Generic.Dictionary<string, object?> updateUpDownCounterTags = new();

			PopulateUpdateUpDownCounterTags(updateUpDownCounterTags);

			_updateUpDownCounterInstrument = _meter.CreateUpDownCounter<int>(name: "multi.update_up_down_counter", unit: null, description: null, tags: updateUpDownCounterTags);
			global::System.Collections.Generic.Dictionary<string, object?> recordHistogramTags = new();

			PopulateRecordHistogramTags(recordHistogramTags);

			_recordHistogramInstrument = _meter.CreateHistogram<double>(name: "multi.record_histogram", unit: null, description: null, tags: recordHistogramTags);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateIncrementCounterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateAutoIncrementTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateUpdateUpDownCounterTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		partial void PopulateRecordHistogramTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void IncrementCounter(int value)
		{
			if (_incrementCounterInstrument == null)
			{
				return;
			}

			_incrementCounterInstrument.Add(value, tagList: default);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void AutoIncrement()
		{
			if (_autoIncrementInstrument == null)
			{
				return;
			}

			_autoIncrementInstrument.Add(1, tagList: default);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void UpdateUpDownCounter(int value)
		{
			if (_updateUpDownCounterInstrument == null)
			{
				return;
			}

			_updateUpDownCounterInstrument.Add(value, tagList: default);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void RecordHistogram(double value)
		{
			if (_recordHistogramInstrument == null)
			{
				return;
			}

			_recordHistogramInstrument.Record(value, tagList: default);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void GetObservableCounter(global::System.Func<long> valueFunc)
		{
			if (_getObservableCounterInstrument != null)
			{
				return;
			}

			_getObservableCounterInstrument = _meter.CreateObservableCounter<long>("multi.get_observable_counter", valueFunc, unit: null, description: null);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void GetObservableGauge(global::System.Func<double> valueFunc)
		{
			if (_getObservableGaugeInstrument != null)
			{
				return;
			}

			_getObservableGaugeInstrument = _meter.CreateObservableGauge<double>("multi.get_observable_gauge", valueFunc, unit: null, description: null);
		}
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void GetObservableUpDownCounter(global::System.Func<int> valueFunc)
		{
			if (_getObservableUpDownCounterInstrument != null)
			{
				return;
			}

			_getObservableUpDownCounterInstrument = _meter.CreateObservableUpDownCounter<int>("multi.get_observable_up_down_counter", valueFunc, unit: null, description: null);
		}
	}
}
