//HintName: ExcludeAttribute.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

namespace Purview.Telemetry
{

/// <summary>
/// Excludes the method from any activity, logging, or meter generation.
/// <para>
/// <em>Note:</em> You must implement the method yourself when using this attribute through
/// the use of partial classes.
/// </para>
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("PURVIEW_TELEMETRY_ATTRIBUTES")]
sealed class ExcludeAttribute : global::System.Attribute { }
}
