using Purview.Telemetry.SourceGenerator.Helpers;

namespace Purview.Telemetry.SourceGenerator.Templates;

/// <summary>
/// Emits the injected marker-attribute templates via <see cref="CodeWriter"/> instead of
/// loading them from embedded resources. Output is deterministic (no timestamp).
/// </summary>
static class SourceEmitter
{
	public static string Emit(string typeName) =>
		typeName switch
		{
			"Targets" => EmitTargets(),
			"NamingConvention" => EmitNamingConvention(),
			"LogPrefixType" => EmitLogPrefixType(),
			"LoggerGenerationMode" => EmitLoggerGenerationMode(),
			"MeterNameGenerationType" => EmitMeterNameGenerationType(),
			"ActivitySourceAttribute" => EmitActivitySourceAttribute(),
			"ActivitySourceGenerationAttribute" => EmitActivitySourceGenerationAttribute(),
			"ActivityAttribute" => EmitActivityAttribute(),
			"EventAttribute" => EmitEventAttribute(),
			"ContextAttribute" => EmitMarkerAttribute("ContextAttribute", AttributeTargets.Method),
			"BaggageAttribute" => EmitBaggageAttribute(),
			"EscapeAttribute" => EmitMarkerAttribute("EscapeAttribute", AttributeTargets.Parameter),
			"StatusDescriptionAttribute" => EmitMarkerAttribute(
				"StatusDescriptionAttribute",
				AttributeTargets.Parameter
			),
			"TelemetryGenerationAttribute" => EmitTelemetryGenerationAttribute(),
			"TagAttribute" => EmitTagAttribute(),
			"ExcludeAttribute" => EmitMarkerAttribute("ExcludeAttribute", AttributeTargets.Method),
			"ExcludeTargetsAttribute" => EmitExcludeTargetsAttribute(),
			"LoggerGenerationAttribute" => EmitLoggerGenerationAttribute(),
			"LoggerAttribute" => EmitLoggerAttribute(),
			"LogAttribute" => EmitLogAttribute(),
			"ExpandEnumerableAttribute" => EmitExpandEnumerableAttribute(),
			"TraceAttribute" => EmitSpecificLogAttribute("TraceAttribute"),
			"DebugAttribute" => EmitSpecificLogAttribute("DebugAttribute"),
			"InfoAttribute" => EmitSpecificLogAttribute("InfoAttribute"),
			"WarningAttribute" => EmitSpecificLogAttribute("WarningAttribute"),
			"ErrorAttribute" => EmitSpecificLogAttribute("ErrorAttribute"),
			"CriticalAttribute" => EmitSpecificLogAttribute("CriticalAttribute"),
			"MeterGenerationAttribute" => EmitMeterGenerationAttribute(),
			"MeterAttribute" => EmitMeterAttribute(),
			"InstrumentMeasurementAttribute" => EmitMarkerAttribute(
				"InstrumentMeasurementAttribute",
				AttributeTargets.Parameter
			),
			"AutoCounterAttribute" => EmitInstrumentAttribute(
				"AutoCounterAttribute",
				autoIncrement: true,
				observable: false
			),
			"CounterAttribute" => EmitInstrumentAttribute("CounterAttribute", autoIncrement: false, observable: false),
			"UpDownCounterAttribute" => EmitInstrumentAttribute(
				"UpDownCounterAttribute",
				autoIncrement: false,
				observable: false
			),
			"HistogramAttribute" => EmitInstrumentAttribute(
				"HistogramAttribute",
				autoIncrement: false,
				observable: false
			),
			"ObservableCounterAttribute" => EmitInstrumentAttribute(
				"ObservableCounterAttribute",
				autoIncrement: false,
				observable: true
			),
			"ObservableUpDownCounterAttribute" => EmitInstrumentAttribute(
				"ObservableUpDownCounterAttribute",
				autoIncrement: false,
				observable: true
			),
			"ObservableGaugeAttribute" => EmitInstrumentAttribute(
				"ObservableGaugeAttribute",
				autoIncrement: false,
				observable: true
			),
			_ => throw new ArgumentOutOfRangeException(nameof(typeName), typeName, "Unknown template."),
		};

	// ---------------------------------------------------------------------------------------
	// Shared helpers
	// ---------------------------------------------------------------------------------------

	static CodeWriter CreateWriter(bool logging = false)
	{
		var writer = new CodeWriter(GenerationSettings.Create<TelemetrySourceGenerator>());
		writer
			.WriteLine("// <auto-generated />")
			.WriteLine("// This code was generated by the Purview.Telemetry.SourceGenerator.")
			.WriteLine("// Changes to this file will be lost when the source generator runs again.")
			.NewLine()
			.WriteLine("#if !NET48_OR_GREATER && !PURVIEW_TELEMETRY_NON_NULLABLE")
			.WriteLine("#nullable enable")
			.WriteLine("#endif")
			.NewLine()
			.WriteLine("#pragma warning disable 1591")
			.NewLine();

		if (logging)
			writer.WriteLine("#if !EXCLUDE_PURVIEW_TELEMETRY_LOGGING").NewLine();

		return writer;
	}

	static AttributeDeclarationOptions ConditionalAttribute() =>
		new(new TypeIdentity("ConditionalAttribute", "System.Diagnostics"))
		{
			Arguments = [new("\"PURVIEW_TELEMETRY_ATTRIBUTES\"")],
		};

	static AttributeDeclarationOptions SuppressMessageAttribute() =>
		new(new TypeIdentity("SuppressMessageAttribute", "System.Diagnostics.CodeAnalysis"))
		{
			Arguments = [new("\"Design\""), new("\"CA1019:Define accessors for attribute arguments\"")],
		};

	/// <summary>Writes a property whose nullability varies with the target framework.</summary>
	static void WriteProperty(
		CodeWriter writer,
		string type,
		string name,
		bool nullable,
		bool hasDefault = false,
		string? defaultValue = null
	)
	{
		if (!nullable)
		{
			writer.Write("public ").Write(type).Write(' ').Write(name).Write(" { get; set; }");
			if (hasDefault)
				writer.Write(" = ").Write(defaultValue).Write(';');
			writer.WriteLine();
			return;
		}

		writer.WriteLine("#if NET48_OR_GREATER || PURVIEW_TELEMETRY_NON_NULLABLE");
		writer.Write("public ").Write(type).Write(' ').Write(name).Write(" { get; set; }");
		if (hasDefault)
			writer.Write(" = ").Write(defaultValue).Write(';');
		writer.WriteLine().WriteLine("#else");
		writer.Write("public ").Write(type).Write("? ").Write(name).Write(" { get; set; }");
		if (hasDefault)
			writer.Write(" = ").Write(defaultValue).Write(';');
		writer.WriteLine().WriteLine("#endif");
	}

	/// <summary>Writes a nullable string property, conditionally emitting the non-nullable form.</summary>
	static void WriteStringProperty(CodeWriter writer, string name, bool nullable) =>
		WriteProperty(writer, "string", name, nullable);

	/// <summary>Writes a marker attribute (no members) with the standard decorations.</summary>
	static string EmitMarkerAttribute(string typeName, AttributeTargets targets)
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new(typeName, TypeDeclarationAccessibility.Internal) { Attributes = [ConditionalAttribute()] },
			targets,
			static _ => { }
		);

		return writer.ToString();
	}

	// ---------------------------------------------------------------------------------------
	// Enums
	// ---------------------------------------------------------------------------------------

	static string EmitTargets()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer
			.XmlSummary("Determines which telemetry targets a parameter is excluded from.")
			.WriteEnum(
				new TypeDeclarationOptions("Targets", TypeDeclarationAccessibility.Public)
				{
					Attributes = [new AttributeDeclarationOptions(new TypeIdentity("FlagsAttribute", "System"))],
				},
				new EnumFieldDeclarationOptions("None", 0),
				new EnumFieldDeclarationOptions("Activities", 1),
				new EnumFieldDeclarationOptions("Logging", 2),
				new EnumFieldDeclarationOptions("Metrics", 4),
				new EnumFieldDeclarationOptions("All", "Activities | Logging | Metrics")
			);

		return writer.ToString();
	}

	static string EmitNamingConvention()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer
			.XmlSummary("Determines the naming convention used for generated telemetry names.")
			.WriteEnum(
				new TypeDeclarationOptions("NamingConvention", TypeDeclarationAccessibility.Public),
				new EnumFieldDeclarationOptions("Legacy", 0),
				new EnumFieldDeclarationOptions("OpenTelemetry", 1)
			);

		return writer.ToString();
	}

	static string EmitLogPrefixType()
	{
		var writer = CreateWriter(logging: true);
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer
			.XmlSummary("Determines the mode used to generate or override the prefix for the log entry.")
			.WriteEnum(
				new TypeDeclarationOptions("LogPrefixType", TypeDeclarationAccessibility.Public),
				new EnumFieldDeclarationOptions("Default", 0),
				new EnumFieldDeclarationOptions("Interface", 1),
				new EnumFieldDeclarationOptions("Class", 2),
				new EnumFieldDeclarationOptions("Custom", 3),
				new EnumFieldDeclarationOptions("TrimmedClassName", 4)
			);

		writer.WriteLine("#endif");
		return writer.ToString();
	}

	static string EmitLoggerGenerationMode()
	{
		var writer = CreateWriter(logging: true);
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer
			.XmlSummary("Controls the generation mode used for log methods.")
			.WriteEnum(
				new TypeDeclarationOptions("LoggerGenerationMode", TypeDeclarationAccessibility.Public),
				new EnumFieldDeclarationOptions("Auto", 0),
				new EnumFieldDeclarationOptions("V1", 1),
				new EnumFieldDeclarationOptions("V2", 2)
			);

		writer.WriteLine("#endif");
		return writer.ToString();
	}

	static string EmitMeterNameGenerationType()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer
			.XmlSummary("Determines how meter names are generated when not explicitly specified.")
			.WriteEnum(
				new TypeDeclarationOptions("MeterNameGenerationType", TypeDeclarationAccessibility.Public),
				new EnumFieldDeclarationOptions("OpenTelemetry", 0),
				new EnumFieldDeclarationOptions("DotNet", 1)
			);

		return writer.ToString();
	}

	// ---------------------------------------------------------------------------------------
	// Activities
	// ---------------------------------------------------------------------------------------

	static string EmitActivitySourceAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("ActivitySourceAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Interface,
			body =>
			{
				body.XmlSummary("Constructs a new instance of the <see cref=\"ActivitySourceAttribute\"/>.")
					.WriteConstructor(
						new("ActivitySourceAttribute", TypeDeclarationAccessibility.Public),
						static constructorWriter => constructorWriter.Comment("Empty")
					)
					.XmlSummary("Constructs a new instance specifying the <see cref=\"Name\"/>.")
					.XmlParam("name", "The <see cref=\"Name\"/>.")
					.WriteConstructor(
						new("ActivitySourceAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("name", PurviewTypeLibrary.System.String)],
						},
						static constructorWriter => constructorWriter.WriteLine("Name = name;")
					);

				WriteStringProperty(body, "Name", nullable: true);
				body.XmlSummary("Specifies the default when inferring between tag or baggage.")
					.WriteProperty(
						new("DefaultToTags", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
						{
							HasSetter = true,
							Initializer = "true",
						}
					);
				WriteStringProperty(body, "BaggageAndTagPrefix", nullable: true);
				body.XmlSummary("Determines if the name is used as a prefix.")
					.WriteProperty(
						new(
							"IncludeActivitySourcePrefix",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					)
					.XmlSummary("Determines if tag/ baggage names are lowercased.")
					.WriteProperty(
						new(
							"LowercaseBaggageAndTagKeys",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					);
			}
		);

		return writer.ToString();
	}

	static string EmitActivitySourceGenerationAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("ActivitySourceGenerationAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Assembly,
			body =>
			{
				body.WriteConstructor(
					new("ActivitySourceGenerationAttribute", TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new("name", PurviewTypeLibrary.System.String),
							new("defaultToTags", PurviewTypeLibrary.System.Boolean) { DefaultValue = "true" },
							new("generateDiagnosticsForMissingActivity", PurviewTypeLibrary.System.Boolean)
							{
								DefaultValue = "true",
							},
						],
					},
					static constructorWriter =>
						constructorWriter
							.WriteLine(
								"if (string.IsNullOrWhiteSpace(name)) throw new System.ArgumentNullException(nameof(name));"
							)
							.WriteAssignment("Name", "name")
							.WriteAssignment("DefaultToTags", "defaultToTags")
							.WriteAssignment(
								"GenerateDiagnosticsForMissingActivity",
								"generateDiagnosticsForMissingActivity"
							)
				);

				WriteStringProperty(body, "Name", nullable: true);
				body.WriteProperty(
					new("DefaultToTags", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
					{
						HasSetter = true,
						Initializer = "true",
					}
				);
				WriteStringProperty(body, "BaggageAndTagPrefix", nullable: true);
				WriteProperty(body, "string", "BaggageAndTagSeparator", false, true, "\".\"");
				body.WriteProperty(
						new(
							"LowercaseBaggageAndTagKeys",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					)
					.WriteProperty(
						new(
							"GenerateDiagnosticsForMissingActivity",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					);
			}
		);

		return writer.ToString();
	}

	static string EmitActivityAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("ActivityAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Method,
			body =>
			{
				body.WriteConstructor(
						new("ActivityAttribute", TypeDeclarationAccessibility.Public),
						static w => w.Comment("Empty")
					)
					.WriteConstructor(
						new("ActivityAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("name", PurviewTypeLibrary.System.String)],
						},
						static constructorWriter => constructorWriter.WriteAssignment("Name", "name")
					)
					.WriteConstructor(
						new("ActivityAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("kind", TypeLibrary.Activities.SystemDiagnostics.ActivityKind.AsTypeReference()),
							],
						},
						static constructorWriter => constructorWriter.WriteAssignment("Kind", "kind")
					)
					.WriteConstructor(
						new("ActivityAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("name", PurviewTypeLibrary.System.String),
								new("kind", TypeLibrary.Activities.SystemDiagnostics.ActivityKind.AsTypeReference())
								{
									DefaultValue = "global::System.Diagnostics.ActivityKind.Internal",
								},
								new("createOnly", PurviewTypeLibrary.System.Boolean) { DefaultValue = "false" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Name", "name")
								.WriteAssignment("Kind", "kind")
								.WriteAssignment("CreateOnly", "createOnly")
					);

				WriteStringProperty(body, "Name", nullable: true);
				body.WriteProperty(
					new(
						"Kind",
						TypeLibrary.Activities.SystemDiagnostics.ActivityKind.AsTypeReference(),
						TypeDeclarationAccessibility.Public
					)
					{
						HasSetter = true,
					}
				);
				body.WriteProperty(
					new("CreateOnly", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
					{
						HasSetter = true,
					}
				);
			}
		);

		return writer.ToString();
	}

	static string EmitEventAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("EventAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Method,
			body =>
			{
				body.WriteConstructor(
						new("EventAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new(
									"statusCode",
									TypeLibrary.Activities.SystemDiagnostics.ActivityStatusCode.AsTypeReference()
								)
								{
									DefaultValue = "global::System.Diagnostics.ActivityStatusCode.Unset",
								},
							],
						},
						static constructorWriter => constructorWriter.WriteAssignment("StatusCode", "statusCode")
					)
					.WriteConstructor(
						new("EventAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("name", PurviewTypeLibrary.System.String),
								new("useRecordExceptionRules", PurviewTypeLibrary.System.Boolean)
								{
									DefaultValue = "true",
								},
								new("recordExceptionAsEscaped", PurviewTypeLibrary.System.Boolean)
								{
									DefaultValue = "true",
								},
								new(
									"statusCode",
									TypeLibrary.Activities.SystemDiagnostics.ActivityStatusCode.AsTypeReference()
								)
								{
									DefaultValue = "global::System.Diagnostics.ActivityStatusCode.Unset",
								},
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Name", "name")
								.WriteAssignment("UseRecordExceptionRules", "useRecordExceptionRules")
								.WriteAssignment("RecordExceptionAsEscaped", "recordExceptionAsEscaped")
								.WriteAssignment("StatusCode", "statusCode")
					);

				WriteStringProperty(body, "Name", nullable: true);
				body.WriteProperty(
						new(
							"UseRecordExceptionRules",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					)
					.WriteProperty(
						new(
							"RecordExceptionAsEscaped",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					)
					.WriteProperty(
						new(
							"StatusCode",
							TypeLibrary.Activities.SystemDiagnostics.ActivityStatusCode.AsTypeReference(),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					);
				WriteStringProperty(body, "StatusDescription", nullable: true);
			}
		);

		return writer.ToString();
	}

	static string EmitBaggageAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("BaggageAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Parameter,
			body =>
			{
				body.WriteConstructor(
						new("BaggageAttribute", TypeDeclarationAccessibility.Public),
						static w => w.Comment("Empty")
					)
					.WriteConstructor(
						new("BaggageAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("skipOnNullOrEmpty", PurviewTypeLibrary.System.Boolean)],
						},
						static constructorWriter =>
							constructorWriter.WriteAssignment("SkipOnNullOrEmpty", "skipOnNullOrEmpty")
					)
					.WriteConstructor(
						new("BaggageAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("name", PurviewTypeLibrary.System.String),
								new("skipOnNullOrEmpty", PurviewTypeLibrary.System.Boolean) { DefaultValue = "false" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Name", "name")
								.WriteAssignment("SkipOnNullOrEmpty", "skipOnNullOrEmpty")
					);

				WriteStringProperty(body, "Name", nullable: true);
				body.WriteProperty(
					new("SkipOnNullOrEmpty", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
					{
						HasSetter = true,
					}
				);
			}
		);

		return writer.ToString();
	}

	static string EmitTagAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("TagAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Parameter,
			body =>
			{
				body.WriteConstructor(
						new("TagAttribute", TypeDeclarationAccessibility.Public),
						static w => w.Comment("Empty")
					)
					.WriteConstructor(
						new("TagAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("skipOnNullOrEmpty", PurviewTypeLibrary.System.Boolean)],
						},
						static constructorWriter =>
							constructorWriter.WriteAssignment("SkipOnNullOrEmpty", "skipOnNullOrEmpty")
					)
					.WriteConstructor(
						new("TagAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("name", PurviewTypeLibrary.System.String),
								new("skipOnNullOrEmpty", PurviewTypeLibrary.System.Boolean) { DefaultValue = "false" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Name", "name")
								.WriteAssignment("SkipOnNullOrEmpty", "skipOnNullOrEmpty")
					);

				WriteStringProperty(body, "Name", nullable: true);
				body.WriteProperty(
					new("SkipOnNullOrEmpty", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
					{
						HasSetter = true,
					}
				);
			}
		);

		return writer.ToString();
	}

	static string EmitExcludeTargetsAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("ExcludeTargetsAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute()],
			},
			AttributeTargets.Parameter,
			body =>
			{
				body.XmlSummary("Constructs a new instance with the specified targets to exclude.")
					.WriteConstructor(
						new("ExcludeTargetsAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("targets", new TypeReference(new TypeIdentity("Targets", "Purview.Telemetry"))),
							],
						},
						static constructorWriter => constructorWriter.WriteAssignment("ExcludedTargets", "targets")
					);

				body.XmlSummary("Gets or sets the targets to exclude for this parameter.")
					.WriteProperty(
						new(
							"ExcludedTargets",
							new TypeReference(new TypeIdentity("Targets", "Purview.Telemetry")),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					);
			}
		);

		return writer.ToString();
	}

	// ---------------------------------------------------------------------------------------
	// Logging
	// ---------------------------------------------------------------------------------------

	static string EmitTelemetryGenerationAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("TelemetryGenerationAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Assembly | AttributeTargets.Interface,
			body =>
			{
				body.WriteConstructor(
						new("TelemetryGenerationAttribute", TypeDeclarationAccessibility.Public),
						static w => w.Comment("Empty")
					)
					.WriteConstructor(
						new("TelemetryGenerationAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("generateDependencyExtension", PurviewTypeLibrary.System.Boolean),
								new("className", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("dependencyInjectionClassName", PurviewTypeLibrary.System.String)
								{
									DefaultValue = "null",
								},
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("GenerateDependencyExtension", "generateDependencyExtension")
								.WriteAssignment("ClassName", "className")
								.WriteAssignment("DependencyInjectionClassName", "dependencyInjectionClassName")
					)
					.WriteConstructor(
						new("TelemetryGenerationAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("className", PurviewTypeLibrary.System.String),
								new("dependencyInjectionClassName", PurviewTypeLibrary.System.String)
								{
									DefaultValue = "null",
								},
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("ClassName", "className")
								.WriteAssignment("DependencyInjectionClassName", "dependencyInjectionClassName")
					);

				body.WriteProperty(
					new(
						"GenerateDependencyExtension",
						PurviewTypeLibrary.System.Boolean,
						TypeDeclarationAccessibility.Public
					)
					{
						HasSetter = true,
						Initializer = "true",
					}
				);
				WriteStringProperty(body, "ClassName", nullable: true);
				WriteStringProperty(body, "DependencyInjectionClassName", nullable: true);
				body.WriteProperty(
						new(
							"DependencyInjectionClassIsPublic",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					)
					.WriteProperty(
						new(
							"NamingConvention",
							new TypeReference(new TypeIdentity("NamingConvention", "Purview.Telemetry")),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "global::Purview.Telemetry.NamingConvention.OpenTelemetry",
						}
					)
					.WriteProperty(
						new(
							"GenerateTelemetryNamesClass",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					);
				WriteStringProperty(body, "TelemetryNamesClassName", nullable: true);
			}
		);

		return writer.ToString();
	}

	static string EmitLoggerGenerationAttribute()
	{
		var writer = CreateWriter(logging: true);
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("LoggerGenerationAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Assembly,
			body =>
			{
				body.WriteConstructor(
						new("LoggerGenerationAttribute", TypeDeclarationAccessibility.Public),
						static w => w.Comment("Empty")
					)
					.WriteConstructor(
						new("LoggerGenerationAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("defaultLevel", TypeLibrary.Logging.MicrosoftExtensions.LogLevel.AsTypeReference()),
							],
						},
						static constructorWriter => constructorWriter.WriteAssignment("DefaultLevel", "defaultLevel")
					);

				body.WriteProperty(
						new(
							"DefaultLevel",
							TypeLibrary.Logging.MicrosoftExtensions.LogLevel.AsTypeReference(),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "global::Microsoft.Extensions.Logging.LogLevel.Information",
						}
					)
					.WriteProperty(
						new(
							"GenerationMode",
							new TypeReference(new TypeIdentity("LoggerGenerationMode", "Purview.Telemetry")),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					)
					.WriteProperty(
						new(
							"DefaultPrefixType",
							new TypeReference(new TypeIdentity("LogPrefixType", "Purview.Telemetry")),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					);
			}
		);

		writer.WriteLine("#endif");
		return writer.ToString();
	}

	static string EmitLoggerAttribute()
	{
		var writer = CreateWriter(logging: true);
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("LoggerAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Interface,
			body =>
			{
				body.WriteConstructor(
						new("LoggerAttribute", TypeDeclarationAccessibility.Public),
						static w => w.Comment("Empty")
					)
					.WriteConstructor(
						new("LoggerAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("defaultLevel", TypeLibrary.Logging.MicrosoftExtensions.LogLevel.AsTypeReference()),
								new("customPrefix", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("DefaultLevel", "defaultLevel")
								.WriteAssignment("CustomPrefix", "customPrefix")
								.WriteLine("if (!string.IsNullOrWhiteSpace(CustomPrefix))")
								.WriteBlock(
									null,
									inner =>
										inner.WriteAssignment(
											"PrefixType",
											"global::Purview.Telemetry.LogPrefixType.Custom"
										)
								)
					);

				body.WriteProperty(
					new(
						"DefaultLevel",
						TypeLibrary.Logging.MicrosoftExtensions.LogLevel.AsTypeReference(),
						TypeDeclarationAccessibility.Public
					)
					{
						HasSetter = true,
						Initializer = "global::Microsoft.Extensions.Logging.LogLevel.Information",
					}
				);
				WriteStringProperty(body, "CustomPrefix", nullable: true);
				body.WriteProperty(
						new(
							"PrefixType",
							new TypeReference(new TypeIdentity("LogPrefixType", "Purview.Telemetry")),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					)
					.WriteProperty(
						new(
							"GenerationMode",
							new TypeReference(new TypeIdentity("LoggerGenerationMode", "Purview.Telemetry")),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					);
			}
		);

		writer.WriteLine("#endif");
		return writer.ToString();
	}

	static string EmitLogAttribute()
	{
		var writer = CreateWriter(logging: true);
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("LogAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Method,
			body =>
			{
				body.WriteConstructor(
						new("LogAttribute", TypeDeclarationAccessibility.Public),
						static w => w.Comment("Empty")
					)
					.WriteConstructor(
						new("LogAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("messageTemplate", PurviewTypeLibrary.System.String)],
						},
						static constructorWriter =>
							constructorWriter.WriteAssignment("MessageTemplate", "messageTemplate")
					)
					.WriteConstructor(
						new("LogAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("eventId", PurviewTypeLibrary.System.Int32)],
						},
						static constructorWriter => constructorWriter.WriteAssignment("EventId", "eventId")
					)
					.WriteConstructor(
						new("LogAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("level", TypeLibrary.Logging.MicrosoftExtensions.LogLevel.AsTypeReference()),
								new("messageTemplate", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("name", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Level", "level")
								.WriteAssignment("MessageTemplate", "messageTemplate")
								.WriteAssignment("Name", "name")
					)
					.WriteConstructor(
						new("LogAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("eventId", PurviewTypeLibrary.System.Int32),
								new("level", TypeLibrary.Logging.MicrosoftExtensions.LogLevel.AsTypeReference()),
								new("messageTemplate", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("name", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Level", "level")
								.WriteAssignment("MessageTemplate", "messageTemplate")
								.WriteAssignment("EventId", "eventId")
								.WriteAssignment("Name", "name")
					);

				body.WriteProperty(
					new(
						"Level",
						TypeLibrary.Logging.MicrosoftExtensions.LogLevel.AsTypeReference(),
						TypeDeclarationAccessibility.Public
					)
					{
						HasSetter = true,
						Initializer = "global::Microsoft.Extensions.Logging.LogLevel.Information",
					}
				);
				WriteStringProperty(body, "MessageTemplate", nullable: true);
				body.WriteProperty(
						new("EventId", TypeReference.Create<int?>(), TypeDeclarationAccessibility.Public)
						{
							HasSetter = true,
						}
					)
					.WriteProperty(
						new(
							"Name",
							PurviewTypeLibrary.System.String.MakeNullable(),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					)
					.WriteProperty(
						new(
							"GenerationMode",
							new TypeReference(new TypeIdentity("LoggerGenerationMode", "Purview.Telemetry")),
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					);
			}
		);

		writer.WriteLine("#endif");
		return writer.ToString();
	}

	static string EmitSpecificLogAttribute(string typeName)
	{
		var writer = CreateWriter(logging: true);
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new(typeName, TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Method,
			body =>
			{
				body.WriteConstructor(
						new(typeName, TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("messageTemplate", PurviewTypeLibrary.System.String)],
						},
						static constructorWriter =>
							constructorWriter.WriteAssignment("MessageTemplate", "messageTemplate")
					)
					.WriteConstructor(
						new(typeName, TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("eventId", PurviewTypeLibrary.System.Int32)],
						},
						static constructorWriter => constructorWriter.WriteAssignment("EventId", "eventId")
					)
					.WriteConstructor(
						new(typeName, TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("messageTemplate", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("name", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("MessageTemplate", "messageTemplate")
								.WriteAssignment("Name", "name")
					)
					.WriteConstructor(
						new(typeName, TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("eventId", PurviewTypeLibrary.System.Int32),
								new("messageTemplate", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("name", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("MessageTemplate", "messageTemplate")
								.WriteAssignment("EventId", "eventId")
								.WriteAssignment("Name", "name")
					);

				WriteStringProperty(body, "MessageTemplate", nullable: true);
				body.WriteProperty(
					new("EventId", TypeReference.Create<int?>(), TypeDeclarationAccessibility.Public)
					{
						HasSetter = true,
					}
				);
				WriteStringProperty(body, "Name", nullable: true);
				body.WriteProperty(
					new(
						"GenerationMode",
						new TypeReference(new TypeIdentity("LoggerGenerationMode", "Purview.Telemetry")),
						TypeDeclarationAccessibility.Public
					)
					{
						HasSetter = true,
					}
				);
			}
		);

		writer.WriteLine("#endif");
		return writer.ToString();
	}

	static string EmitExpandEnumerableAttribute()
	{
		var writer = CreateWriter(logging: true);
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("ExpandEnumerableAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Parameter,
			body =>
			{
				body.WriteConstructor(
					new("ExpandEnumerableAttribute", TypeDeclarationAccessibility.Public)
					{
						Parameters = [new("maximumValueCount", PurviewTypeLibrary.System.Int32) { DefaultValue = "5" }],
					},
					static constructorWriter =>
						constructorWriter.WriteAssignment("MaximumValueCount", "maximumValueCount")
				);

				body.XmlSummary("Gets or sets the maximum number of values to include when expanding an enumerable.")
					.WriteProperty(
						new("MaximumValueCount", PurviewTypeLibrary.System.Int32, TypeDeclarationAccessibility.Public)
						{
							HasSetter = true,
						}
					);
			}
		);

		writer.WriteLine("#endif");
		return writer.ToString();
	}

	// ---------------------------------------------------------------------------------------
	// Metrics
	// ---------------------------------------------------------------------------------------

	static string EmitMeterGenerationAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("MeterGenerationAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Assembly,
			body =>
			{
				body.WriteConstructor(
					new("MeterGenerationAttribute", TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new("meterName", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
							new(
								"nameGenerationType",
								new TypeReference(new TypeIdentity("MeterNameGenerationType", "Purview.Telemetry"))
							)
							{
								DefaultValue = "global::Purview.Telemetry.MeterNameGenerationType.DotNet",
							},
							new("instrumentPrefix", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
							new("lowercaseInstrumentName", PurviewTypeLibrary.System.Boolean) { DefaultValue = "true" },
							new("lowercaseTagKeys", PurviewTypeLibrary.System.Boolean) { DefaultValue = "true" },
						],
					},
					static constructorWriter =>
						constructorWriter
							.WriteAssignment("MeterName", "meterName")
							.WriteAssignment("MeterNameGenerationType", "nameGenerationType")
							.WriteAssignment("InstrumentPrefix", "instrumentPrefix")
							.WriteAssignment("LowercaseInstrumentName", "lowercaseInstrumentName")
							.WriteAssignment("LowercaseTagKeys", "lowercaseTagKeys")
				);

				WriteStringProperty(body, "MeterName", nullable: true);
				body.WriteProperty(
					new(
						"MeterNameGenerationType",
						new TypeReference(new TypeIdentity("MeterNameGenerationType", "Purview.Telemetry")),
						TypeDeclarationAccessibility.Public
					)
					{
						HasSetter = true,
						Initializer = "global::Purview.Telemetry.MeterNameGenerationType.DotNet",
					}
				);
				WriteStringProperty(body, "InstrumentPrefix", nullable: true);
				WriteProperty(body, "string", "InstrumentSeparator", false, true, "\".\"");
				body.WriteProperty(
						new(
							"LowercaseInstrumentName",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					)
					.WriteProperty(
						new("LowercaseTagKeys", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
						{
							HasSetter = true,
							Initializer = "true",
						}
					);
			}
		);

		return writer.ToString();
	}

	static string EmitMeterAttribute()
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new("MeterAttribute", TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Interface,
			body =>
			{
				body.WriteConstructor(
						new("MeterAttribute", TypeDeclarationAccessibility.Public),
						static w => w.Comment("Empty")
					)
					.WriteConstructor(
						new("MeterAttribute", TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("name", PurviewTypeLibrary.System.String)],
						},
						static constructorWriter => constructorWriter.WriteAssignment("Name", "name")
					);

				WriteStringProperty(body, "Name", nullable: true);
				WriteStringProperty(body, "InstrumentPrefix", nullable: true);
				body.WriteProperty(
						new(
							"IncludeAssemblyInstrumentPrefix",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					)
					.WriteProperty(
						new(
							"LowercaseInstrumentName",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
							Initializer = "true",
						}
					)
					.WriteProperty(
						new("LowercaseTagKeys", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
						{
							HasSetter = true,
							Initializer = "true",
						}
					);
			}
		);

		return writer.ToString();
	}

	static string EmitInstrumentAttribute(string typeName, bool autoIncrement, bool observable)
	{
		var writer = CreateWriter();
		writer.WriteFileScopedNamespace("Purview.Telemetry");
		writer.WriteAttributeClass(
			new(typeName, TypeDeclarationAccessibility.Internal)
			{
				IsSealed = true,
				Attributes = [ConditionalAttribute(), SuppressMessageAttribute()],
			},
			AttributeTargets.Method,
			body =>
			{
				body.WriteConstructor(
					new(typeName, TypeDeclarationAccessibility.Public),
					static w => w.Comment("Empty")
				);

				if (autoIncrement)
				{
					body.WriteConstructor(
						new(typeName, TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("name", PurviewTypeLibrary.System.String),
								new("unit", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("description", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Name", "name")
								.WriteAssignment("Unit", "unit")
								.WriteAssignment("Description", "description")
					);
				}
				else if (observable)
				{
					body.WriteConstructor(
						new(typeName, TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("name", PurviewTypeLibrary.System.String),
								new("unit", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("description", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("throwOnAlreadyInitialized", PurviewTypeLibrary.System.Boolean)
								{
									DefaultValue = "false",
								},
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Name", "name")
								.WriteAssignment("Unit", "unit")
								.WriteAssignment("Description", "description")
								.WriteAssignment("ThrowOnAlreadyInitialized", "throwOnAlreadyInitialized")
					);
				}
				else
				{
					body.WriteConstructor(
						new(typeName, TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("autoIncrement", PurviewTypeLibrary.System.Boolean)],
						},
						static constructorWriter => constructorWriter.WriteAssignment("AutoIncrement", "autoIncrement")
					);
					body.WriteConstructor(
						new(typeName, TypeDeclarationAccessibility.Public)
						{
							Parameters =
							[
								new("name", PurviewTypeLibrary.System.String),
								new("unit", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("description", PurviewTypeLibrary.System.String) { DefaultValue = "null" },
								new("autoIncrement", PurviewTypeLibrary.System.Boolean) { DefaultValue = "false" },
							],
						},
						static constructorWriter =>
							constructorWriter
								.WriteAssignment("Name", "name")
								.WriteAssignment("Unit", "unit")
								.WriteAssignment("Description", "description")
								.WriteAssignment("AutoIncrement", "autoIncrement")
					);
				}

				if (!autoIncrement)
					body.WriteProperty(
						new("AutoIncrement", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
						{
							HasSetter = true,
						}
					);

				WriteStringProperty(body, "Name", nullable: true);
				WriteStringProperty(body, "Unit", nullable: true);
				WriteStringProperty(body, "Description", nullable: true);

				if (observable)
					body.WriteProperty(
						new(
							"ThrowOnAlreadyInitialized",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasSetter = true,
						}
					);
			}
		);

		return writer.ToString();
	}
}
