using Microsoft.CodeAnalysis;
using Purview.Telemetry.SourceGenerator.Records;

namespace Purview.Telemetry.SourceGenerator.Emitters;

static partial class ActivitySourceTargetClassEmitter
{
	public static void GenerateImplementation(ActivityOutputContext output, SourceProductionContext context)
	{
		var target = output.Target;
		var logger = output.Context.Logger;
		var emitNullable = output.Context.Capabilities.SupportsNullableAnnotations;

		logger?.Debug($"Generating activity class for: {target.FullyQualifiedName}");

		var writer = output.Context.CreateCodeWriter();
		EmitterHelpers.WriteAutoGeneratedHeader(writer, emitNullable);

		using (writer.WriteBlockNamespaceScope(target.ClassNamespace))
		{
			List<CodeWriter.BlockScope> parentScopes = [];
			foreach (var parent in target.ParentClasses)
			{
				parentScopes.Add(
					writer.WriteClassScope(new(parent) { IsSealed = false, IncludeGeneratedAttributes = false })
				);
			}

			using (
				EmitterHelpers.EmitClassScope(
					writer,
					GenerationType.Activities,
					target.GenerationType,
					target.ClassNameToGenerate,
					target.InterfaceType,
					TypeDeclarationAccessibility.Internal
				)
			)
			{
				EmitFields(target, writer, context, logger);
				EmitMethods(target, writer, context, logger, emitNullable);
			}

			foreach (var scope in parentScopes)
				scope.Dispose();
		}

		context.AddSource($"{target.FullyQualifiedName}.Activity.g.cs", writer);

		DependencyInjectionClassEmitter.GenerateImplementation(
			GenerationType.Activities,
			target.TelemetryGeneration,
			target.GenerationType,
			target.ClassNameToGenerate,
			target.InterfaceType.Identity.Name,
			target.FullNamespace,
			context,
			output.Context
		);
	}
}
