using Microsoft.CodeAnalysis;
using Purview.Telemetry.SourceGenerator.Helpers;
using Purview.Telemetry.SourceGenerator.Records;

namespace Purview.Telemetry.SourceGenerator.Emitters;

static partial class ActivitySourceTargetClassEmitter
{
	public static void GenerateImplementation(
		ActivitySourceTarget target,
		SourceProductionContext context,
		GenerationLogger? logger,
		bool emitNullable = true
	)
	{
		logger?.Debug($"Generating activity class for: {target.FullyQualifiedName}");

		var writer = new CodeWriter(GenerationSettings.Create<TelemetrySourceGenerator>());
		EmitterHelpers.WriteAutoGeneratedHeader(writer, emitNullable);

		using (writer.WriteBlockNamespaceScope(target.ClassNamespace))
		{
			List<CodeWriter.BlockScope> parentScopes = [];
			foreach (var parent in target.ParentClasses)
			{
				parentScopes.Add(
					writer.WriteClassScope(
						new TypeDeclarationOptions(parent) { IsSealed = false, IncludeGeneratedAttributes = false }
					)
				);
			}

			using (
				EmitterHelpers.EmitClassScope(
					writer,
					GenerationType.Activities,
					target.GenerationType,
					target.ClassNameToGenerate,
					EmitterHelpers.AsTypeReference(target.InterfaceType),
					TypeDeclarationAccessibility.Internal
				)
			)
			{
				EmitFields(target, writer, context, logger);
				EmitMethods(target, writer, context, logger, emitNullable);
			}

			foreach (var scope in parentScopes)
				scope.Dispose();
		}

		context.AddSource($"{target.FullyQualifiedName}.Activity.g.cs", writer);

		DependencyInjectionClassEmitter.GenerateImplementation(
			GenerationType.Activities,
			target.TelemetryGeneration,
			target.GenerationType,
			target.ClassNameToGenerate,
			target.InterfaceType.TypeName,
			target.FullNamespace,
			context,
			logger,
			emitNullable
		);
	}
}
