using Microsoft.CodeAnalysis;
using Purview.Telemetry.SourceGenerator.Helpers;
using Purview.Telemetry.SourceGenerator.Records;

namespace Purview.Telemetry.SourceGenerator.Emitters;

static class DependencyInjectionClassEmitter
{
	public static void GenerateImplementation(
		GenerationType requestingType,
		TelemetryGenerationAttributeRecord attribute,
		GenerationType generationType,
		string implementationClassName,
		string sourceInterfaceName,
		string? fullyQualifiedNamespace,
		SourceProductionContext context,
		GenerationLogger? logger,
		bool emitNullable = true
	)
	{
		context.CancellationToken.ThrowIfCancellationRequested();

		if (attribute.GenerateDependencyExtension.Value == false)
		{
			logger?.Debug("Skipping dependency injection emit.");
			return;
		}

		if (!SharedHelpers.ShouldEmitDIExtension(requestingType, generationType))
		{
			logger?.Debug($"Skipping dependency injection emit for {requestingType} ({generationType}).");
			return;
		}

		var classNameToGenerate = attribute.DependencyInjectionClassName.Value;
		if (string.IsNullOrWhiteSpace(classNameToGenerate))
			classNameToGenerate = implementationClassName + "DIExtension";

		var classAccessibility =
			(attribute.DependencyInjectionClassIsPublic.Value ?? false)
				? TypeDeclarationAccessibility.Public
				: TypeDeclarationAccessibility.Internal;

		logger?.Debug(
			$"Generating service dependency class {classNameToGenerate} for: {fullyQualifiedNamespace}{sourceInterfaceName}"
		);

		context.CancellationToken.ThrowIfCancellationRequested();

		var writer = new CodeWriter(GenerationSettings.Create<TelemetrySourceGenerator>());
		EmitterHelpers.WriteAutoGeneratedHeader(writer, emitNullable);

		using (writer.WriteBlockNamespaceScope(Constants.DependencyInjection.DependencyInjectionNamespace))
		{
			writer
				.WriteLine(Constants.System.EditorBrowsableConstant)
				.WriteLine(Constants.System.ExcludeFromCodeCoverageConstant)
				.WriteLine(Constants.System.GeneratedCode.Value);

			using (
				writer.WriteClassScope(
					new TypeDeclarationOptions(classNameToGenerate, classAccessibility)
					{
						IsStatic = true,
						IncludeGeneratedAttributes = false,
					}
				)
			)
			{
				EmitMethod(
					writer,
					implementationClassName,
					sourceInterfaceName,
					fullyQualifiedNamespace,
					logger,
					context.CancellationToken
				);
			}
		}

		var hintName = $"{fullyQualifiedNamespace}{classNameToGenerate}.DependencyInjection.g.cs";
		context.AddSource(hintName, writer);
	}

	static void EmitMethod(
		CodeWriter writer,
		string className,
		string interfaceName,
		string? fullyQualifiedNamespace,
		GenerationLogger? logger,
		CancellationToken token
	)
	{
		token.ThrowIfCancellationRequested();

		logger?.Debug($"Emitting DI method for {interfaceName}.");

		var methodName = interfaceName;
		if (methodName[0] == 'I')
			methodName = methodName.Substring(1);

		writer
			.WriteLine(Constants.System.GeneratedCode.Value)
			.WriteLine(Constants.System.AggressiveInlining)
			.Write("public static ")
			.Write(Constants.DependencyInjection.IServiceCollection)
			.Write(" Add")
			.Write(methodName)
			.Write("(this ")
			.Write(Constants.DependencyInjection.IServiceCollection)
			.WriteLine(" services)");

		using (writer.OpenBlockScope())
		{
			writer
				.Write("return services.AddSingleton<")
				.Write("global::")
				.Write(fullyQualifiedNamespace)
				.Write(interfaceName)
				.Write(", ")
				.Write("global::")
				.Write(fullyQualifiedNamespace)
				.Write(className)
				.WriteLine(">();");
		}
	}
}
