using Microsoft.CodeAnalysis;
using Purview.Telemetry.SourceGenerator.Helpers;
using Purview.Telemetry.SourceGenerator.Records;

namespace Purview.Telemetry.SourceGenerator.Emitters;

static partial class LoggerGenTargetClassEmitter
{
	public static void GenerateImplementation(LoggerOutputContext output, SourceProductionContext context)
	{
		var target = output.Target;
		var logger = output.Context.Logger;
		var emitNullable = output.Context.Capabilities.SupportsNullableAnnotations;
		var supportsIMeterFactory = output.Context.Capabilities.SupportsIMeterFactory;

		logger?.Debug($"Generating MS Gen-based logging class for: {target.FullyQualifiedName}");

		var writer = output.Context.CreateCodeWriter();
		EmitterHelpers.WriteAutoGeneratedHeader(writer, emitNullable);

		using (writer.WriteBlockNamespaceScope(target.ClassNamespace))
		{
			List<CodeWriter.BlockScope> parentScopes = [];
			foreach (var parent in target.ParentClasses)
			{
				parentScopes.Add(
					writer.WriteClassScope(
						new TypeDeclarationOptions(parent) { IsSealed = false, IncludeGeneratedAttributes = false }
					)
				);
			}

			using (
				EmitterHelpers.EmitClassScope(
					writer,
					GenerationType.Logging,
					target.GenerationType,
					target.ClassNameToGenerate,
					target.InterfaceType,
					TypeDeclarationAccessibility.Internal
				)
			)
			{
				EmitFields(target, writer, context, logger, emitNullable);

				ConstructorEmitter.EmitCtor(
					GenerationType.Logging,
					target.GenerationType,
					target.ClassNameToGenerate,
					target.InterfaceType,
					writer,
					context,
					logger,
					supportsIMeterFactory
				);

				EmitMethods(target, writer, context, logger, emitNullable);

				EmitLogStateStructs(target, writer, context, logger, emitNullable);
			}

			foreach (var scope in parentScopes)
				scope.Dispose();
		}

		context.AddSource($"{target.FullyQualifiedName}.Logging.g.cs", writer);

		DependencyInjectionClassEmitter.GenerateImplementation(
			GenerationType.Logging,
			target.TelemetryGeneration,
			target.GenerationType,
			target.ClassNameToGenerate,
			target.InterfaceType.Identity.Name,
			target.FullNamespace,
			context,
			output.Context
		);
	}

	static void EmitFields(
		LoggerTarget target,
		CodeWriter writer,
		SourceProductionContext context,
		ISourceGenLogger? logger,
		bool emitNullable
	)
	{
		context.CancellationToken.ThrowIfCancellationRequested();

		writer
			.Write("readonly ")
			.Write(TypeLibrary.Logging.MicrosoftExtensions.ILogger)
			.Write('<')
			.Write(target.InterfaceType)
			.Write('>')
			.Write(' ')
			.Write(PropertyLibrary.Logging.LoggerFieldName)
			.Write(';')
			.NewLine();

		foreach (var methodTarget in target.LogMethods)
		{
			context.CancellationToken.ThrowIfCancellationRequested();

			if (!methodTarget.TargetGenerationState.IsValid)
				continue;

			if (methodTarget.UnknownReturnType)
			{
				continue;
			}

			// Multiple exceptions is always invalid, regardless of v1 or v2 generation.
			if (methodTarget.HasMultipleExceptions)
			{
				logger?.Diagnostic("Method has multiple exception parameters, only a single one is permitted.");
				continue;
			}

			if (!methodTarget.UseV1Generation)
				continue;

			if (methodTarget.ParameterCountSansException > PropertyLibrary.Logging.MaxNonExceptionParameters)
			{
				logger?.Diagnostic("Method has more than 6 parameters.");
				continue;
			}

			if (methodTarget.InferredErrorLevel)
			{
				logger?.Diagnostic("Inferring error log level.");
			}

			LoggerTargetClassEmitter.EmitLogActionField(writer, methodTarget, emitNullable);
		}
	}
}
