using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Purview.Telemetry.SourceGenerator.Helpers;
using Purview.Telemetry.SourceGenerator.Templates;

namespace Purview.Telemetry.SourceGenerator.Emitters;

/// <summary>
/// Emits the marker-attribute templates injected into consuming compilations. Each template
/// previously shipped as a static embedded resource; it is now built in memory with a
/// <see cref="CodeWriter"/> inside <c>RegisterPostInitializationOutput</c>.
/// </summary>
static class MarkerAttributeTemplateEmitter
{
	static readonly Dictionary<string, Action<CodeWriter, TypeIdentity>> Emitters = new(StringComparer.Ordinal)
	{
		["TagAttribute"] = WriteTagLikeAttribute,
		["BaggageAttribute"] = WriteTagLikeAttribute,
		["ExcludeAttribute"] = (writer, type) =>
			WriteSimpleAttribute(writer, type, AttributeTargets.Method, includeSuppressMessage: false),
		["TelemetryGenerationAttribute"] = WriteTelemetryGenerationAttribute,
		["Targets"] = WriteTargetsEnum,
		["NamingConvention"] = WriteNamingConventionEnum,
		["ExcludeTargetsAttribute"] = WriteExcludeTargetsAttribute,
		["ActivitySourceGenerationAttribute"] = WriteActivitySourceGenerationAttribute,
		["ActivitySourceAttribute"] = WriteActivitySourceAttribute,
		["ActivityAttribute"] = WriteActivityAttribute,
		["EventAttribute"] = WriteEventAttribute,
		["ContextAttribute"] = (writer, type) =>
			WriteSimpleAttribute(writer, type, AttributeTargets.Method, includeSuppressMessage: false),
		["EscapeAttribute"] = (writer, type) =>
			WriteSimpleAttribute(writer, type, AttributeTargets.Parameter, includeSuppressMessage: false),
		["StatusDescriptionAttribute"] = (writer, type) =>
			WriteSimpleAttribute(writer, type, AttributeTargets.Parameter, includeSuppressMessage: false),
		["LoggerGenerationAttribute"] = WriteLoggerGenerationAttribute,
		["LoggerAttribute"] = WriteLoggerAttribute,
		["LogAttribute"] = WriteLogAttribute,
		["LogPrefixType"] = WriteLogPrefixTypeEnum,
		["LoggerGenerationMode"] = WriteLoggerGenerationModeEnum,
		["ExpandEnumerableAttribute"] = WriteExpandEnumerableAttribute,
		["TraceAttribute"] = WriteSpecificLogAttribute,
		["DebugAttribute"] = WriteSpecificLogAttribute,
		["InfoAttribute"] = WriteSpecificLogAttribute,
		["WarningAttribute"] = WriteSpecificLogAttribute,
		["ErrorAttribute"] = WriteSpecificLogAttribute,
		["CriticalAttribute"] = WriteSpecificLogAttribute,
		["MeterGenerationAttribute"] = WriteMeterGenerationAttribute,
		["MeterAttribute"] = WriteMeterAttribute,
		["MeterNameGenerationType"] = WriteMeterNameGenerationTypeEnum,
		["InstrumentMeasurementAttribute"] = (writer, type) =>
			WriteSimpleAttribute(writer, type, AttributeTargets.Parameter, includeSuppressMessage: false),
		["AutoCounterAttribute"] = WriteAutoCounterAttribute,
		["CounterAttribute"] = WriteCounterLikeAttribute,
		["UpDownCounterAttribute"] = WriteCounterLikeAttribute,
		["HistogramAttribute"] = WriteCounterLikeAttribute,
		["ObservableCounterAttribute"] = WriteObservableCounterLikeAttribute,
		["ObservableUpDownCounterAttribute"] = WriteObservableCounterLikeAttribute,
		["ObservableGaugeAttribute"] = WriteObservableCounterLikeAttribute,
	};

	public static void EmitAll(IncrementalGeneratorPostInitializationContext context)
	{
		var settings = GenerationSettings.Create<TelemetrySourceGenerator>();

		foreach (var template in TemplateLibrary.GetAllTemplates())
		{
			var writer = new CodeWriter(settings);
			Emit(writer, template);
			context.AddSource(template.GetGeneratedFilename(), SourceText.From(writer.ToString(), Encoding.UTF8));
		}
	}

	static void Emit(CodeWriter writer, TemplateInfo template)
	{
		if (!Emitters.TryGetValue(template.Name, out var emit))
			throw new ArgumentOutOfRangeException(
				nameof(template),
				template.Name,
				"Unknown marker-attribute template."
			);

		emit(writer, template.TypeInfo);
	}

	// -------------------------------------------------------------------------------------------
	// File scaffolding
	// -------------------------------------------------------------------------------------------

	static void WriteHeader(CodeWriter writer)
	{
		writer
			.WriteLine("// <auto-generated />")
			.WriteLine("// This code was generated by the Purview.Telemetry.SourceGenerator.")
			.WriteLine("// Changes to this file will be lost when the source generator runs again.")
			.NewLine()
			.WriteLine("#if !NET48_OR_GREATER && !PURVIEW_TELEMETRY_NON_NULLABLE")
			.WriteLine("#nullable enable")
			.WriteLine("#endif")
			.NewLine()
			.WriteLine("#pragma warning disable 1591")
			.NewLine();
	}

	static void WriteFileScopedNamespace(CodeWriter writer) => writer.WriteFileScopedNamespace("Purview.Telemetry");

	// -------------------------------------------------------------------------------------------
	// Attribute templates
	// -------------------------------------------------------------------------------------------

	/// <summary>Writes a complete attribute-template file.</summary>
	static void EmitAttribute(
		CodeWriter writer,
		TypeIdentity type,
		AttributeTargets targets,
		Action<CodeWriter> body,
		bool wrapInExcludeLoggingGuard = false,
		bool includeSuppressMessage = true
	)
	{
		WriteHeader(writer);

		if (wrapInExcludeLoggingGuard)
			writer.WriteLine("#if !EXCLUDE_PURVIEW_TELEMETRY_LOGGING").NewLine();

		WriteFileScopedNamespace(writer);
		WriteAttributeTemplate(writer, type, targets, body, includeSuppressMessage);

		if (wrapInExcludeLoggingGuard)
			writer.WriteLine("#endif");
	}

	static void WriteAttributeTemplate(
		CodeWriter writer,
		TypeIdentity type,
		AttributeTargets targets,
		Action<CodeWriter> body,
		bool includeSuppressMessage
	)
	{
		var attributes = ImmutableArray<AttributeDeclarationOptions>.Empty;
		attributes = attributes.Add(ConditionalAttribute());
		if (includeSuppressMessage)
			attributes = attributes.Add(SuppressMessageAttribute());

		writer.WriteAttributeClass(
			new TypeDeclarationOptions(type.Name, TypeDeclarationAccessibility.Internal) { Attributes = attributes },
			targets,
			body
		);
	}

	static void WriteSimpleAttribute(
		CodeWriter writer,
		TypeIdentity type,
		AttributeTargets targets,
		bool includeSuppressMessage
	)
	{
		EmitAttribute(writer, type, targets, static _ => { }, includeSuppressMessage: includeSuppressMessage);
	}

	static AttributeDeclarationOptions ConditionalAttribute() =>
		new(new TypeIdentity("ConditionalAttribute", "System.Diagnostics"))
		{
			Arguments = [new AttributeArgumentOptions("\"PURVIEW_TELEMETRY_ATTRIBUTES\"")],
		};

	static AttributeDeclarationOptions SuppressMessageAttribute() =>
		new(new TypeIdentity("SuppressMessageAttribute", "System.Diagnostics.CodeAnalysis"))
		{
			Arguments =
			[
				new AttributeArgumentOptions("\"Design\""),
				new AttributeArgumentOptions("\"CA1019:Define accessors for attribute arguments\""),
			],
		};

	// -------------------------------------------------------------------------------------------
	// Members
	// -------------------------------------------------------------------------------------------

	static void WriteEmptyConstructor(CodeWriter writer, TypeIdentity type) =>
		writer.WriteConstructor(
			new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public),
			static _ => { }
		);

	static void WriteNameConstructor(CodeWriter writer, TypeIdentity type) =>
		writer.WriteConstructor(
			new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
			{
				Parameters = [new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference())],
			},
			ctor => ctor.WriteAssignment("Name", "name")
		);

	static void WriteMessageTemplateConstructor(CodeWriter writer, TypeIdentity type) =>
		writer.WriteConstructor(
			new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
			{
				Parameters =
				[
					new ParameterDeclarationOptions("messageTemplate", TypeLibrary.System.String.AsTypeReference()),
				],
			},
			ctor => ctor.WriteAssignment("MessageTemplate", "messageTemplate")
		);

	static void WriteEventIdConstructor(CodeWriter writer, TypeIdentity type) =>
		writer.WriteConstructor(
			new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
			{
				Parameters = [new ParameterDeclarationOptions("eventId", TypeLibrary.System.Int32.AsTypeReference())],
			},
			ctor => ctor.WriteAssignment("EventId", "eventId")
		);

	/// <summary>Writes a public property with generated attributes and an optional initializer.</summary>
	static void WritePublicProperty(CodeWriter writer, string name, TypeReference type, string? initializer = null)
	{
		writer.WriteProperty(
			new PropertyDeclarationOptions(name, type, TypeDeclarationAccessibility.Public)
			{
				HasSetter = true,
				Initializer = initializer,
			}
		);
	}

	/// <summary>
	/// Writes a public nullable-capable string property inside the <c>NET48_OR_GREATER</c>/
	/// <c>PURVIEW_TELEMETRY_NON_NULLABLE</c> preprocessor guard used by the marker attributes.
	/// </summary>
	static void WriteNullableStringProperty(CodeWriter writer, string name)
	{
		writer.WriteLine("#if NET48_OR_GREATER || PURVIEW_TELEMETRY_NON_NULLABLE");
		writer.WriteProperty(
			new PropertyDeclarationOptions(
				name,
				TypeLibrary.System.String.AsTypeReference(),
				TypeDeclarationAccessibility.Public
			)
			{
				HasSetter = true,
				IncludeGeneratedAttributes = false,
			}
		);
		writer.WriteLine("#else");
		writer.WriteProperty(
			new PropertyDeclarationOptions(
				name,
				TypeLibrary.System.String.AsTypeReference().Nullable(),
				TypeDeclarationAccessibility.Public
			)
			{
				HasSetter = true,
				IncludeGeneratedAttributes = false,
			}
		);
		writer.WriteLine("#endif");
	}

	/// <summary>Writes a public non-nullable string property (used for defaults that always have a value).</summary>
	static void WritePlainStringProperty(CodeWriter writer, string name, string? initializer = null)
	{
		writer.WriteProperty(
			new PropertyDeclarationOptions(
				name,
				TypeLibrary.System.String.AsTypeReference(),
				TypeDeclarationAccessibility.Public
			)
			{
				HasSetter = true,
				IncludeGeneratedAttributes = false,
				Initializer = initializer,
			}
		);
	}

	// -------------------------------------------------------------------------------------------
	// Shared templates
	// -------------------------------------------------------------------------------------------

	static void WriteTagLikeAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Parameter,
			body =>
			{
				WriteEmptyConstructor(body, type);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions(
								"skipOnNullOrEmpty",
								TypeLibrary.System.Boolean.AsTypeReference()
							),
						],
					},
					ctor => ctor.WriteAssignment("SkipOnNullOrEmpty", "skipOnNullOrEmpty")
				);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference()),
							new ParameterDeclarationOptions(
								"skipOnNullOrEmpty",
								TypeLibrary.System.Boolean.AsTypeReference()
							)
							{
								DefaultValue = "false",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("Name", "name");
						ctor.WriteAssignment("SkipOnNullOrEmpty", "skipOnNullOrEmpty");
					}
				);

				WriteNullableStringProperty(body, "Name");
				WritePublicProperty(body, "SkipOnNullOrEmpty", TypeLibrary.System.Boolean.AsTypeReference());
			}
		);
	}

	static void WriteTelemetryGenerationAttribute(CodeWriter writer, TypeIdentity type)
	{
		var namingConvention = TypeLibrary.Telemetry.NamingConventionEnum;

		EmitAttribute(
			writer,
			type,
			AttributeTargets.Assembly | AttributeTargets.Interface,
			body =>
			{
				WriteEmptyConstructor(body, type);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions(
								"generateDependencyExtension",
								TypeLibrary.System.Boolean.AsTypeReference()
							),
							new ParameterDeclarationOptions("className", TypeLibrary.System.String.AsTypeReference())
							{
								DefaultValue = "null",
							},
							new ParameterDeclarationOptions(
								"dependencyInjectionClassName",
								TypeLibrary.System.String.AsTypeReference()
							)
							{
								DefaultValue = "null",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("GenerateDependencyExtension", "generateDependencyExtension");
						ctor.WriteAssignment("ClassName", "className");
						ctor.WriteAssignment("DependencyInjectionClassName", "dependencyInjectionClassName");
					}
				);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("className", TypeLibrary.System.String.AsTypeReference()),
							new ParameterDeclarationOptions(
								"dependencyInjectionClassName",
								TypeLibrary.System.String.AsTypeReference()
							)
							{
								DefaultValue = "null",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("ClassName", "className");
						ctor.WriteAssignment("DependencyInjectionClassName", "dependencyInjectionClassName");
					}
				);

				WritePublicProperty(
					body,
					"GenerateDependencyExtension",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				WriteNullableStringProperty(body, "ClassName");
				WriteNullableStringProperty(body, "DependencyInjectionClassName");
				WritePublicProperty(
					body,
					"DependencyInjectionClassIsPublic",
					TypeLibrary.System.Boolean.AsTypeReference()
				);
				WritePublicProperty(
					body,
					"NamingConvention",
					namingConvention.AsTypeReference(),
					$"{namingConvention.RenderFullName}.OpenTelemetry"
				);
				WritePublicProperty(
					body,
					"GenerateTelemetryNamesClass",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				WriteNullableStringProperty(body, "TelemetryNamesClassName");
			}
		);
	}

	static void WriteExcludeTargetsAttribute(CodeWriter writer, TypeIdentity type)
	{
		var targets = TypeLibrary.Telemetry.TargetsEnum;

		EmitAttribute(
			writer,
			type,
			AttributeTargets.Parameter,
			body =>
			{
				body.XmlSummary("Constructs a new instance with the specified targets to exclude.");
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters = [new ParameterDeclarationOptions("targets", targets.AsTypeReference())],
					},
					ctor => ctor.WriteAssignment("ExcludedTargets", "targets")
				);

				body.XmlSummary("Gets or sets the targets to exclude for this parameter.");
				WritePublicProperty(body, "ExcludedTargets", targets.AsTypeReference());
			}
		);
	}

	// -------------------------------------------------------------------------------------------
	// Activity templates
	// -------------------------------------------------------------------------------------------

	static void WriteActivitySourceGenerationAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Assembly,
			body =>
			{
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference()),
							new ParameterDeclarationOptions(
								"defaultToTags",
								TypeLibrary.System.Boolean.AsTypeReference()
							)
							{
								DefaultValue = "true",
							},
							new ParameterDeclarationOptions(
								"generateDiagnosticsForMissingActivity",
								TypeLibrary.System.Boolean.AsTypeReference()
							)
							{
								DefaultValue = "true",
							},
						],
					},
					ctor =>
					{
						ctor.WriteLine(
							"if (string.IsNullOrWhiteSpace(name)) throw new System.ArgumentNullException(nameof(name));"
						);
						ctor.WriteAssignment("Name", "name");
						ctor.WriteAssignment("DefaultToTags", "defaultToTags");
						ctor.WriteAssignment(
							"GenerateDiagnosticsForMissingActivity",
							"generateDiagnosticsForMissingActivity"
						);
					}
				);

				WriteNullableStringProperty(body, "Name");
				WritePublicProperty(body, "DefaultToTags", TypeLibrary.System.Boolean.AsTypeReference(), "true");
				WriteNullableStringProperty(body, "BaggageAndTagPrefix");
				WritePlainStringProperty(body, "BaggageAndTagSeparator", "\".\"");
				WritePublicProperty(
					body,
					"LowercaseBaggageAndTagKeys",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				WritePublicProperty(
					body,
					"GenerateDiagnosticsForMissingActivity",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
			}
		);
	}

	static void WriteActivitySourceAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Interface,
			body =>
			{
				body.XmlSummary($"Constructs a new instance of the {XmlSee("ActivitySourceAttribute")}.");
				WriteEmptyConstructor(body, type);

				body.XmlSummary($"Constructs a new instance specifying the {XmlSee("Name")}.");
				body.XmlParam("name", $"The {XmlSee("Name")}.");
				WriteNameConstructor(body, type);

				WriteNullableStringProperty(body, "Name");
				body.XmlSummary("Specifies the default when inferring between tag or baggage.");
				WritePublicProperty(body, "DefaultToTags", TypeLibrary.System.Boolean.AsTypeReference(), "true");
				WriteNullableStringProperty(body, "BaggageAndTagPrefix");
				body.XmlSummary("Determines if the name is used as a prefix.");
				WritePublicProperty(
					body,
					"IncludeActivitySourcePrefix",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				body.XmlSummary("Determines if tag/ baggage names are lowercased.");
				WritePublicProperty(
					body,
					"LowercaseBaggageAndTagKeys",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
			}
		);
	}

	static void WriteActivityAttribute(CodeWriter writer, TypeIdentity type)
	{
		var activityKind = TypeLibrary.Activities.SystemDiagnostics.ActivityKind;

		EmitAttribute(
			writer,
			type,
			AttributeTargets.Method,
			body =>
			{
				WriteEmptyConstructor(body, type);
				WriteNameConstructor(body, type);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters = [new ParameterDeclarationOptions("kind", activityKind.AsTypeReference())],
					},
					ctor => ctor.WriteAssignment("Kind", "kind")
				);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference()),
							new ParameterDeclarationOptions("kind", activityKind.AsTypeReference())
							{
								DefaultValue = $"{activityKind.RenderFullName}.Internal",
							},
							new ParameterDeclarationOptions("createOnly", TypeLibrary.System.Boolean.AsTypeReference())
							{
								DefaultValue = "false",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("Name", "name");
						ctor.WriteAssignment("Kind", "kind");
						ctor.WriteAssignment("CreateOnly", "createOnly");
					}
				);

				WriteNullableStringProperty(body, "Name");
				WritePublicProperty(body, "Kind", activityKind.AsTypeReference());
				WritePublicProperty(body, "CreateOnly", TypeLibrary.System.Boolean.AsTypeReference());
			}
		);
	}

	static void WriteEventAttribute(CodeWriter writer, TypeIdentity type)
	{
		var statusCode = TypeLibrary.Activities.SystemDiagnostics.ActivityStatusCode;

		EmitAttribute(
			writer,
			type,
			AttributeTargets.Method,
			body =>
			{
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("statusCode", statusCode.AsTypeReference())
							{
								DefaultValue = $"{statusCode.RenderFullName}.Unset",
							},
						],
					},
					ctor => ctor.WriteAssignment("StatusCode", "statusCode")
				);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference()),
							new ParameterDeclarationOptions(
								"useRecordExceptionRules",
								TypeLibrary.System.Boolean.AsTypeReference()
							)
							{
								DefaultValue = "true",
							},
							new ParameterDeclarationOptions(
								"recordExceptionAsEscaped",
								TypeLibrary.System.Boolean.AsTypeReference()
							)
							{
								DefaultValue = "true",
							},
							new ParameterDeclarationOptions("statusCode", statusCode.AsTypeReference())
							{
								DefaultValue = $"{statusCode.RenderFullName}.Unset",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("Name", "name");
						ctor.WriteAssignment("UseRecordExceptionRules", "useRecordExceptionRules");
						ctor.WriteAssignment("RecordExceptionAsEscaped", "recordExceptionAsEscaped");
						ctor.WriteAssignment("StatusCode", "statusCode");
					}
				);

				WriteNullableStringProperty(body, "Name");
				WritePublicProperty(
					body,
					"UseRecordExceptionRules",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				WritePublicProperty(
					body,
					"RecordExceptionAsEscaped",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				WritePublicProperty(body, "StatusCode", statusCode.AsTypeReference());
				WriteNullableStringProperty(body, "StatusDescription");
			}
		);
	}

	// -------------------------------------------------------------------------------------------
	// Logging templates
	// -------------------------------------------------------------------------------------------

	static void WriteLoggerGenerationAttribute(CodeWriter writer, TypeIdentity type)
	{
		var logLevel = TypeLibrary.Logging.MicrosoftExtensions.LogLevel;

		EmitAttribute(
			writer,
			type,
			AttributeTargets.Assembly,
			body =>
			{
				WriteEmptyConstructor(body, type);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters = [new ParameterDeclarationOptions("defaultLevel", logLevel.AsTypeReference())],
					},
					ctor => ctor.WriteAssignment("DefaultLevel", "defaultLevel")
				);

				WritePublicProperty(
					body,
					"DefaultLevel",
					logLevel.AsTypeReference(),
					$"{logLevel.RenderFullName}.Information"
				);
				WritePublicProperty(body, "GenerationMode", TypeLibrary.Logging.LoggerGenerationMode.AsTypeReference());
				WritePublicProperty(body, "DefaultPrefixType", TypeLibrary.Logging.LogPrefixType.AsTypeReference());
			},
			wrapInExcludeLoggingGuard: true
		);
	}

	static void WriteLoggerAttribute(CodeWriter writer, TypeIdentity type)
	{
		var logLevel = TypeLibrary.Logging.MicrosoftExtensions.LogLevel;
		var logPrefixType = TypeLibrary.Logging.LogPrefixType;

		EmitAttribute(
			writer,
			type,
			AttributeTargets.Interface,
			body =>
			{
				WriteEmptyConstructor(body, type);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("defaultLevel", logLevel.AsTypeReference()),
							new ParameterDeclarationOptions("customPrefix", TypeLibrary.System.String.AsTypeReference())
							{
								DefaultValue = "null",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("DefaultLevel", "defaultLevel");
						ctor.WriteAssignment("CustomPrefix", "customPrefix");
						ctor.WriteIfBlock(
							"!string.IsNullOrWhiteSpace(CustomPrefix)",
							block => block.WriteAssignment("PrefixType", $"{logPrefixType.RenderFullName}.Custom")
						);
					}
				);

				WritePublicProperty(
					body,
					"DefaultLevel",
					logLevel.AsTypeReference(),
					$"{logLevel.RenderFullName}.Information"
				);
				WriteNullableStringProperty(body, "CustomPrefix");
				WritePublicProperty(body, "PrefixType", logPrefixType.AsTypeReference());
				WritePublicProperty(body, "GenerationMode", TypeLibrary.Logging.LoggerGenerationMode.AsTypeReference());
			},
			wrapInExcludeLoggingGuard: true
		);
	}

	static void WriteLogAttribute(CodeWriter writer, TypeIdentity type)
	{
		var logLevel = TypeLibrary.Logging.MicrosoftExtensions.LogLevel;

		EmitAttribute(
			writer,
			type,
			AttributeTargets.Method,
			body =>
			{
				WriteEmptyConstructor(body, type);
				WriteMessageTemplateConstructor(body, type);
				WriteEventIdConstructor(body, type);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("level", logLevel.AsTypeReference()),
							new ParameterDeclarationOptions(
								"messageTemplate",
								TypeLibrary.System.String.AsTypeReference()
							)
							{
								DefaultValue = "null",
							},
							new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference())
							{
								DefaultValue = "null",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("Level", "level");
						ctor.WriteAssignment("MessageTemplate", "messageTemplate");
						ctor.WriteAssignment("Name", "name");
					}
				);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("eventId", TypeLibrary.System.Int32.AsTypeReference()),
							new ParameterDeclarationOptions("level", logLevel.AsTypeReference()),
							new ParameterDeclarationOptions(
								"messageTemplate",
								TypeLibrary.System.String.AsTypeReference()
							)
							{
								DefaultValue = "null",
							},
							new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference())
							{
								DefaultValue = "null",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("Level", "level");
						ctor.WriteAssignment("MessageTemplate", "messageTemplate");
						ctor.WriteAssignment("EventId", "eventId");
						ctor.WriteAssignment("Name", "name");
					}
				);

				WritePublicProperty(
					body,
					"Level",
					logLevel.AsTypeReference(),
					$"{logLevel.RenderFullName}.Information"
				);
				WriteNullableStringProperty(body, "MessageTemplate");
				WritePublicProperty(body, "EventId", TypeLibrary.System.Int32.AsTypeReference().Nullable());
				WritePublicProperty(body, "Name", TypeLibrary.System.String.AsTypeReference().Nullable());
				WritePublicProperty(body, "GenerationMode", TypeLibrary.Logging.LoggerGenerationMode.AsTypeReference());
			},
			wrapInExcludeLoggingGuard: true
		);
	}

	static void WriteSpecificLogAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Method,
			body =>
			{
				WriteMessageTemplateConstructor(body, type);
				WriteEventIdConstructor(body, type);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions(
								"messageTemplate",
								TypeLibrary.System.String.AsTypeReference()
							)
							{
								DefaultValue = "null",
							},
							new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference())
							{
								DefaultValue = "null",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("MessageTemplate", "messageTemplate");
						ctor.WriteAssignment("Name", "name");
					}
				);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("eventId", TypeLibrary.System.Int32.AsTypeReference()),
							new ParameterDeclarationOptions(
								"messageTemplate",
								TypeLibrary.System.String.AsTypeReference()
							)
							{
								DefaultValue = "null",
							},
							new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference())
							{
								DefaultValue = "null",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("MessageTemplate", "messageTemplate");
						ctor.WriteAssignment("EventId", "eventId");
						ctor.WriteAssignment("Name", "name");
					}
				);

				WriteNullableStringProperty(body, "MessageTemplate");
				WritePublicProperty(body, "EventId", TypeLibrary.System.Int32.AsTypeReference().Nullable());
				WriteNullableStringProperty(body, "Name");
				WritePublicProperty(body, "GenerationMode", TypeLibrary.Logging.LoggerGenerationMode.AsTypeReference());
			},
			wrapInExcludeLoggingGuard: true
		);
	}

	static void WriteExpandEnumerableAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Parameter,
			body =>
			{
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions(
								"maximumValueCount",
								TypeLibrary.System.Int32.AsTypeReference()
							)
							{
								DefaultValue = "5",
							},
						],
					},
					ctor => ctor.WriteAssignment("MaximumValueCount", "maximumValueCount")
				);

				body.XmlSummary("Gets or sets the maximum number of values to include when expanding an enumerable.");
				WritePublicProperty(body, "MaximumValueCount", TypeLibrary.System.Int32.AsTypeReference());
			},
			wrapInExcludeLoggingGuard: true
		);
	}

	// -------------------------------------------------------------------------------------------
	// Metrics templates
	// -------------------------------------------------------------------------------------------

	static void WriteMeterGenerationAttribute(CodeWriter writer, TypeIdentity type)
	{
		var nameGenerationType = TypeLibrary.Metrics.MeterNameGenerationType;

		EmitAttribute(
			writer,
			type,
			AttributeTargets.Assembly,
			body =>
			{
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions("meterName", TypeLibrary.System.String.AsTypeReference())
							{
								DefaultValue = "null",
							},
							new ParameterDeclarationOptions("nameGenerationType", nameGenerationType.AsTypeReference())
							{
								DefaultValue = $"{nameGenerationType.RenderFullName}.DotNet",
							},
							new ParameterDeclarationOptions(
								"instrumentPrefix",
								TypeLibrary.System.String.AsTypeReference()
							)
							{
								DefaultValue = "null",
							},
							new ParameterDeclarationOptions(
								"lowercaseInstrumentName",
								TypeLibrary.System.Boolean.AsTypeReference()
							)
							{
								DefaultValue = "true",
							},
							new ParameterDeclarationOptions(
								"lowercaseTagKeys",
								TypeLibrary.System.Boolean.AsTypeReference()
							)
							{
								DefaultValue = "true",
							},
						],
					},
					ctor =>
					{
						ctor.WriteAssignment("MeterName", "meterName");
						ctor.WriteAssignment("MeterNameGenerationType", "nameGenerationType");
						ctor.WriteAssignment("InstrumentPrefix", "instrumentPrefix");
						ctor.WriteAssignment("LowercaseInstrumentName", "lowercaseInstrumentName");
						ctor.WriteAssignment("LowercaseTagKeys", "lowercaseTagKeys");
					}
				);

				WriteNullableStringProperty(body, "MeterName");
				WritePublicProperty(
					body,
					"MeterNameGenerationType",
					nameGenerationType.AsTypeReference(),
					$"{nameGenerationType.RenderFullName}.DotNet"
				);
				WriteNullableStringProperty(body, "InstrumentPrefix");
				WritePlainStringProperty(body, "InstrumentSeparator", "\".\"");
				WritePublicProperty(
					body,
					"LowercaseInstrumentName",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				WritePublicProperty(body, "LowercaseTagKeys", TypeLibrary.System.Boolean.AsTypeReference(), "true");
			}
		);
	}

	static void WriteMeterAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Interface,
			body =>
			{
				WriteEmptyConstructor(body, type);
				WriteNameConstructor(body, type);

				WriteNullableStringProperty(body, "Name");
				WriteNullableStringProperty(body, "InstrumentPrefix");
				WritePublicProperty(
					body,
					"IncludeAssemblyInstrumentPrefix",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				WritePublicProperty(
					body,
					"LowercaseInstrumentName",
					TypeLibrary.System.Boolean.AsTypeReference(),
					"true"
				);
				WritePublicProperty(body, "LowercaseTagKeys", TypeLibrary.System.Boolean.AsTypeReference(), "true");
			}
		);
	}

	static void WriteAutoCounterAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Method,
			body =>
			{
				WriteEmptyConstructor(body, type);
				WriteNameUnitDescriptionConstructor(body, type);

				WriteNullableStringProperty(body, "Name");
				WriteNullableStringProperty(body, "Unit");
				WriteNullableStringProperty(body, "Description");
			}
		);
	}

	static void WriteCounterLikeAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Method,
			body =>
			{
				WriteEmptyConstructor(body, type);
				body.WriteConstructor(
					new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new ParameterDeclarationOptions(
								"autoIncrement",
								TypeLibrary.System.Boolean.AsTypeReference()
							),
						],
					},
					ctor => ctor.WriteAssignment("AutoIncrement", "autoIncrement")
				);
				WriteNameUnitDescriptionConstructor(body, type, appendAutoIncrement: true);

				WritePublicProperty(body, "AutoIncrement", TypeLibrary.System.Boolean.AsTypeReference());
				WriteNullableStringProperty(body, "Name");
				WriteNullableStringProperty(body, "Unit");
				WriteNullableStringProperty(body, "Description");
			}
		);
	}

	static void WriteObservableCounterLikeAttribute(CodeWriter writer, TypeIdentity type)
	{
		EmitAttribute(
			writer,
			type,
			AttributeTargets.Method,
			body =>
			{
				WriteEmptyConstructor(body, type);
				WriteNameUnitDescriptionConstructor(body, type, appendThrowOnAlreadyInitialized: true);

				WritePublicProperty(body, "AutoIncrement", TypeLibrary.System.Boolean.AsTypeReference());
				WriteNullableStringProperty(body, "Name");
				WriteNullableStringProperty(body, "Unit");
				WriteNullableStringProperty(body, "Description");
				WritePublicProperty(body, "ThrowOnAlreadyInitialized", TypeLibrary.System.Boolean.AsTypeReference());
			}
		);
	}

	static void WriteNameUnitDescriptionConstructor(
		CodeWriter writer,
		TypeIdentity type,
		bool appendAutoIncrement = false,
		bool appendThrowOnAlreadyInitialized = false
	)
	{
		writer.WriteConstructor(
			new ConstructorDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
			{
				Parameters = BuildNameUnitDescriptionParameters(appendAutoIncrement, appendThrowOnAlreadyInitialized),
			},
			ctor =>
			{
				ctor.WriteAssignment("Name", "name");
				ctor.WriteAssignment("Unit", "unit");
				ctor.WriteAssignment("Description", "description");
				if (appendAutoIncrement)
					ctor.WriteAssignment("AutoIncrement", "autoIncrement");
				if (appendThrowOnAlreadyInitialized)
					ctor.WriteAssignment("ThrowOnAlreadyInitialized", "throwOnAlreadyInitialized");
			}
		);
	}

	static ImmutableArray<ParameterDeclarationOptions> BuildNameUnitDescriptionParameters(
		bool appendAutoIncrement,
		bool appendThrowOnAlreadyInitialized
	)
	{
		var parameters = ImmutableArray<ParameterDeclarationOptions>.Empty;
		parameters = parameters.Add(
			new ParameterDeclarationOptions("name", TypeLibrary.System.String.AsTypeReference())
		);
		parameters = parameters.Add(
			new ParameterDeclarationOptions("unit", TypeLibrary.System.String.AsTypeReference())
			{
				DefaultValue = "null",
			}
		);
		parameters = parameters.Add(
			new ParameterDeclarationOptions("description", TypeLibrary.System.String.AsTypeReference())
			{
				DefaultValue = "null",
			}
		);
		if (appendAutoIncrement)
			parameters = parameters.Add(
				new ParameterDeclarationOptions("autoIncrement", TypeLibrary.System.Boolean.AsTypeReference())
				{
					DefaultValue = "false",
				}
			);
		if (appendThrowOnAlreadyInitialized)
			parameters = parameters.Add(
				new ParameterDeclarationOptions(
					"throwOnAlreadyInitialized",
					TypeLibrary.System.Boolean.AsTypeReference()
				)
				{
					DefaultValue = "false",
				}
			);

		return parameters;
	}

	// -------------------------------------------------------------------------------------------
	// Enum templates
	// -------------------------------------------------------------------------------------------

	static void WriteTargetsEnum(CodeWriter writer, TypeIdentity type)
	{
		WriteHeader(writer);
		WriteFileScopedNamespace(writer);

		writer.XmlSummary("Determines which telemetry targets a parameter is excluded from.");
		writer.WriteEnum(
			new TypeDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public)
			{
				Attributes = [new AttributeDeclarationOptions(new TypeIdentity("FlagsAttribute", "System"))],
			},
			new EnumFieldDeclarationOptions("None", 0),
			new EnumFieldDeclarationOptions("Activities", 1),
			new EnumFieldDeclarationOptions("Logging", 2),
			new EnumFieldDeclarationOptions("Metrics", 4),
			new EnumFieldDeclarationOptions("All", "Activities | Logging | Metrics")
		);
	}

	static void WriteNamingConventionEnum(CodeWriter writer, TypeIdentity type)
	{
		WriteHeader(writer);
		WriteFileScopedNamespace(writer);

		writer.XmlSummary("Determines the naming convention used for generated telemetry names.");
		writer.WriteEnum(
			new TypeDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public),
			new EnumFieldDeclarationOptions("Legacy", 0),
			new EnumFieldDeclarationOptions("OpenTelemetry", 1)
		);
	}

	static void WriteLogPrefixTypeEnum(CodeWriter writer, TypeIdentity type)
	{
		WriteHeader(writer);
		writer.WriteLine("#if !EXCLUDE_PURVIEW_TELEMETRY_LOGGING").NewLine();
		WriteFileScopedNamespace(writer);

		writer.XmlSummary("Determines the mode used to generate or override the prefix for the log entry.");
		writer.WriteEnum(
			new TypeDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public),
			new EnumFieldDeclarationOptions("Default", 0),
			new EnumFieldDeclarationOptions("Interface", 1),
			new EnumFieldDeclarationOptions("Class", 2),
			new EnumFieldDeclarationOptions("Custom", 3),
			new EnumFieldDeclarationOptions("TrimmedClassName", 4)
		);

		writer.WriteLine("#endif");
	}

	static void WriteLoggerGenerationModeEnum(CodeWriter writer, TypeIdentity type)
	{
		WriteHeader(writer);
		writer.WriteLine("#if !EXCLUDE_PURVIEW_TELEMETRY_LOGGING").NewLine();
		WriteFileScopedNamespace(writer);

		writer.XmlSummary("Controls the generation mode used for log methods.");
		writer.WriteEnum(
			new TypeDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public),
			new EnumFieldDeclarationOptions("Auto", 0),
			new EnumFieldDeclarationOptions("V1", 1),
			new EnumFieldDeclarationOptions("V2", 2)
		);

		writer.WriteLine("#endif");
	}

	static void WriteMeterNameGenerationTypeEnum(CodeWriter writer, TypeIdentity type)
	{
		WriteHeader(writer);
		WriteFileScopedNamespace(writer);

		writer.XmlSummary("Determines how meter names are generated when not explicitly specified.");
		writer.WriteEnum(
			new TypeDeclarationOptions(type.Name, TypeDeclarationAccessibility.Public),
			new EnumFieldDeclarationOptions("OpenTelemetry", 0),
			new EnumFieldDeclarationOptions("DotNet", 1)
		);
	}
}
