using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Purview.Telemetry.SourceGenerator.Helpers;

namespace Purview.Telemetry.SourceGenerator.Emitters;

static class TelemetryNamesEmitter
{
	public static void GenerateClass(
		ImmutableArray<string> meterNames,
		ImmutableArray<string> activitySourceNames,
		string className,
		string? rootNamespace,
		bool emitNullable,
		SourceProductionContext spc,
		GenerationLogger? logger
	)
	{
		logger?.Debug($"Generating Telemetry Names using class '{className}'.");

		var writer = new CodeWriter(GenerationSettings.Create<TelemetrySourceGenerator>());
		EmitterHelpers.WriteAutoGeneratedHeader(writer, emitNullable);

		var hasNamespace = !string.IsNullOrWhiteSpace(rootNamespace);

		using (writer.WriteBlockNamespaceScope(rootNamespace))
		{
			writer
				.WriteLine(Constants.System.EditorBrowsableConstant)
				.WriteLine(Constants.System.ExcludeFromCodeCoverageConstant)
				.WriteLine(Constants.System.GeneratedCode.Value);

			using (
				writer.WriteClassScope(
					new TypeDeclarationOptions(className, TypeDeclarationAccessibility.Internal)
					{
						IsStatic = true,
						IncludeGeneratedAttributes = false,
					}
				)
			)
			{
				writer.Write("public static readonly string[] MeterNames = ");
				WriteStringArray(writer, meterNames);

				writer.NewLine().Write("public static readonly string[] ActivitySourceNames = ");
				WriteStringArray(writer, activitySourceNames);
			}
		}

		var hintName = $"{className}.g.cs";
		if (hasNamespace)
			hintName = $"{rootNamespace}.{hintName}";

		spc.AddSource(hintName, writer);
	}

	static void WriteStringArray(CodeWriter writer, ImmutableArray<string> values)
	{
		if (values.Length == 0)
		{
			writer.WriteLine("global::System.Array.Empty<string>();");
			return;
		}

		writer.WriteLine("new string[]");
		writer.WriteLine("{");
		writer.Indent();
		for (var i = 0; i < values.Length; i++)
		{
			writer.Write("\"").Write(values[i]).Write('"');
			if (i < values.Length - 1)
				writer.Write(',');
			writer.NewLine();
		}
		writer.Unindent();
		writer.WriteLine("};");
	}
}
