using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Purview.Telemetry.SourceGenerator.Helpers;

namespace Purview.Telemetry.SourceGenerator.Emitters;

static class TelemetryNamesEmitter
{
	public static void GenerateClass(
		ImmutableArray<string> meterNames,
		ImmutableArray<string> activitySourceNames,
		string className,
		string? rootNamespace,
		bool emitNullable,
		SourceProductionContext spc,
		ISourceGenLogger? logger
	)
	{
		logger?.Debug($"Generating Telemetry Names using class '{className}'.");

		var writer = new CodeWriter(GenerationSettings.Create<TelemetrySourceGenerator>());
		EmitterHelpers.WriteAutoGeneratedHeader(writer, emitNullable);

		var hasNamespace = !string.IsNullOrWhiteSpace(rootNamespace);

		using (writer.WriteBlockNamespaceScope(rootNamespace))
		{
			using (
				writer.WriteClassScope(
					new TypeDeclarationOptions(className, TypeDeclarationAccessibility.Internal)
					{
						IsStatic = true,
						IncludeGeneratedAttributes = false,
						Attributes = [EmitterHelpers.EditorBrowsableAttribute()],
					}
				)
			)
			{
				var stringArrayType = TypeLibrary.System.String.AsTypeReference().MakeArray();

				writer.WriteField(
					new FieldDeclarationOptions("MeterNames", stringArrayType, TypeDeclarationAccessibility.Public)
					{
						IsStatic = true,
						IsReadOnly = true,
						Initializer = BuildArrayInitializer(meterNames),
						IncludeGeneratedAttributes = false,
					}
				);

				writer.WriteField(
					new FieldDeclarationOptions(
						"ActivitySourceNames",
						stringArrayType,
						TypeDeclarationAccessibility.Public
					)
					{
						IsStatic = true,
						IsReadOnly = true,
						Initializer = BuildArrayInitializer(activitySourceNames),
						IncludeGeneratedAttributes = false,
					}
				);
			}
		}

		var hintName = $"{className}.g.cs";
		if (hasNamespace)
			hintName = $"{rootNamespace}.{hintName}";

		spc.AddSource(hintName, writer);
	}

	static string BuildArrayInitializer(ImmutableArray<string> values)
	{
		if (values.Length == 0)
			return "global::System.Array.Empty<string>()";

		return "new string[] { " + string.Join(", ", values.Select(v => "\"" + v + "\"")) + " }";
	}
}
