//HintName: Targets.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Purview.Telemetry;

/// <summary>
/// Specifies the telemetry generation target families.
/// Used with <see cref="ExcludeTargetsAttribute"/> to exclude parameters from specific targets.
/// </summary>
[global::System.Flags]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
enum Targets
{
	/// <summary>
	/// No targets.
	/// </summary>
	None = 0,

	/// <summary>
	/// Activities generation target (ActivitySource, Activity, Event, Context).
	/// </summary>
	Activities = 1,

	/// <summary>
	/// Logging generation target (ILogger, Log, Info, Debug, etc.).
	/// </summary>
	Logging = 2,

	/// <summary>
	/// Metrics generation target (Meter, Counter, Histogram, etc.).
	/// </summary>
	Metrics = 4,

	/// <summary>
	/// All telemetry generation targets.
	/// </summary>
	All = Activities | Logging | Metrics
}
