//HintName: Testing.TestLoggerCore.Logging.g.cs
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	sealed partial class TestLoggerCore : global::Testing.ITestLogger
	{
		readonly global::Microsoft.Extensions.Logging.ILogger<global::Testing.ITestLogger> _logger;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestLoggerCore(global::Microsoft.Extensions.Logging.ILogger<global::Testing.ITestLogger> logger)
		{
			_logger = logger;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Log(string stringParam, global::System.Exception exception1, global::System.Exception exception2)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_logger.Log(
				global::Microsoft.Extensions.Logging.LogLevel.Information,
				new (1579320335, nameof(Log)),
				new Log_LogState(stringParam),
				null,
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
				static string (s, _) =>
				{
#if NET
					return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"Log: StringParam = {s._StringParam}");
#else
					return global::System.FormattableString.Invariant($"Log: StringParam = {s._StringParam}");
#endif
				}
			);

		}


	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	private readonly struct Log_LogState : global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.KeyValuePair<string, object?>>
	{
		static readonly string s_originalFormat = "Log: StringParam = {StringParam}";

		public readonly string _StringParam;

		public Log_LogState(string stringParam)
		{
			_StringParam = stringParam;
		}


		public int Count => 2;

		public global::System.Collections.Generic.KeyValuePair<string, object?> this[int index]
		{
			[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
			get => index switch
			{
				0 => new("{OriginalFormat}", s_originalFormat),
				1 => new("stringParam", _StringParam),
				_ => throw new global::System.IndexOutOfRangeException(nameof(index))
			};
		}


		public struct Enumerator : global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>>
		{
			readonly Log_LogState _state;
			int _index;

			public Enumerator(Log_LogState state)
			{
				_state = state;
				_index = -1;
			}

			public global::System.Collections.Generic.KeyValuePair<string, object?> Current => _state[_index];

			object? global::System.Collections.IEnumerator.Current => Current;

			public bool MoveNext() => ++_index < _state.Count;

			public void Reset() => _index = -1;

			public void Dispose() { }
		}


		public Enumerator GetEnumerator() => new Enumerator(this);


		global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object?>>.GetEnumerator() => GetEnumerator();


		global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
	}

	}
}
