<Project Sdk="Aspire.AppHost.Sdk/13.1.0">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsAspireHost>true</IsAspireHost>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.0" />
		<PackageReference Include="Scalar.Aspire" Version="0.8.45" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SampleApp.APIService\SampleApp.APIService.csproj" />
		<ProjectReference Include="..\SampleApp.Web\SampleApp.Web.csproj" />
	</ItemGroup>
</Project>
