//HintName: MultiTargetGenerationTypes.g.cs
//HintName: MultiTargetGenerationTypes.g.cs
// <auto-generated>
//	This code was generated by the Purview.Telemetry.SourceGenerator
//	on {Scrubbed}.
//
//	Changes to this file may cause incorrect behaviour and will be lost
//	when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Purview.Telemetry;

/// <summary>
/// Assembly-level attribute to enable multi-target telemetry generation.
/// When applied to an assembly, allows methods to use <see cref="TelemetryAttribute"/>
/// and related exclusion attributes.
/// </summary>
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("PURVIEW_TELEMETRY_ATTRIBUTES")]
[global::System.Diagnostics.CodeAnalysis.SuppressMessage(
	"Design",
	"CA1019:Define accessors for attribute arguments"
)]
sealed class EnableMultiTargetGenerationAttribute : global::System.Attribute
{
	/// <summary>
	/// Initializes a new instance of the <see cref="EnableMultiTargetGenerationAttribute"/> class.
	/// </summary>
	public EnableMultiTargetGenerationAttribute() { }

	/// <summary>
	/// Determines if backwards compatibility mode is enabled.
	/// When true, existing single-target attributes continue to work alongside multi-target attributes.
	/// When false, only multi-target attributes are supported.
	/// Defaults to true.
	/// </summary>
	public bool BackwardsCompatibility { get; set; } = true;
}

/// <summary>
/// Excludes a parameter from Activity telemetry generation when using multi-target generation.
/// Only applicable when the method has <see cref="TelemetryAttribute"/> with
/// <see cref="TelemetryAttribute.GenerateActivity"/> set to true.
/// </summary>
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("PURVIEW_TELEMETRY_ATTRIBUTES")]
[global::System.Diagnostics.CodeAnalysis.SuppressMessage(
	"Design",
	"CA1019:Define accessors for attribute arguments"
)]
sealed class ExcludeFromActivityAttribute : global::System.Attribute
{
	/// <summary>
	/// Initializes a new instance of the <see cref="ExcludeFromActivityAttribute"/> class.
	/// </summary>
	public ExcludeFromActivityAttribute() { }
}

/// <summary>
/// Excludes a parameter from Metrics telemetry generation when using multi-target generation.
/// Only applicable when the method has <see cref="TelemetryAttribute"/> with
/// <see cref="TelemetryAttribute.GenerateMetrics"/> set to true.
/// </summary>
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("PURVIEW_TELEMETRY_ATTRIBUTES")]
[global::System.Diagnostics.CodeAnalysis.SuppressMessage(
	"Design",
	"CA1019:Define accessors for attribute arguments"
)]
sealed class ExcludeFromMetricsAttribute : global::System.Attribute
{
	/// <summary>
	/// Initializes a new instance of the <see cref="ExcludeFromMetricsAttribute"/> class.
	/// </summary>
	public ExcludeFromMetricsAttribute() { }
}

#if !EXCLUDE_PURVIEW_TELEMETRY_LOGGING

/// <summary>
/// Excludes a parameter from Logging telemetry generation when using multi-target generation.
/// Only applicable when the method has <see cref="TelemetryAttribute"/> with
/// <see cref="TelemetryAttribute.GenerateLogging"/> set to true.
/// </summary>
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("PURVIEW_TELEMETRY_ATTRIBUTES")]
[global::System.Diagnostics.CodeAnalysis.SuppressMessage(
	"Design",
	"CA1019:Define accessors for attribute arguments"
)]
sealed class ExcludeFromLoggingAttribute : global::System.Attribute
{
	/// <summary>
	/// Initializes a new instance of the <see cref="ExcludeFromLoggingAttribute"/> class.
	/// </summary>
	public ExcludeFromLoggingAttribute() { }
}

#endif

/// <summary>
/// Marker attribute to enable multi-target telemetry generation from a single method.
/// Allows generating Activity, Logging, and/or Metrics telemetry from one method.
/// Requires assembly-level opt-in via <see cref="EnableMultiTargetGenerationAttribute"/>.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("PURVIEW_TELEMETRY_ATTRIBUTES")]
[global::System.Diagnostics.CodeAnalysis.SuppressMessage(
	"Design",
	"CA1019:Define accessors for attribute arguments"
)]
sealed class TelemetryAttribute : global::System.Attribute
{
	/// <summary>
	/// Initializes a new instance of the <see cref="TelemetryAttribute"/> class.
	/// </summary>
	public TelemetryAttribute() { }

	/// <summary>
	/// Determines if Activity telemetry should be generated for this method.
	/// </summary>
	public bool GenerateActivity { get; set; }

	/// <summary>
	/// Determines if Metrics telemetry should be generated for this method.
	/// </summary>
	public bool GenerateMetrics { get; set; }

	/// <summary>
	/// Optional name for the Activity. If not specified, uses the method name.
	/// Only used when <see cref="GenerateActivity"/> is true.
	/// </summary>
	public string? ActivityName { get; set; }

	/// <summary>
	/// Optional activity kind for the Activity. Defaults to Internal.
	/// Only used when <see cref="GenerateActivity"/> is true.
	/// </summary>
	public global::System.Diagnostics.ActivityKind ActivityKind { get; set; } = 
		global::System.Diagnostics.ActivityKind.Internal;

	/// <summary>
	/// If true, the Activity is created using CreateActivity (not started by default).
	/// Otherwise StartActivity is used. Only used when <see cref="GenerateActivity"/> is true.
	/// </summary>
	public bool CreateActivityOnly { get; set; }

	/// <summary>
	/// The activity method type. Determines if this is an Activity start/create, Event, or Context method.
	/// Only used when <see cref="GenerateActivity"/> is true.
	/// </summary>
	public ActivityMethodType ActivityMethodType { get; set; } = ActivityMethodType.Activity;

	/// <summary>
	/// Optional activity status code for Event methods. 
	/// Only used when <see cref="GenerateActivity"/> is true and <see cref="ActivityMethodType"/> is Event.
	/// </summary>
	public global::System.Diagnostics.ActivityStatusCode ActivityStatusCode { get; set; } = 
		global::System.Diagnostics.ActivityStatusCode.Unset;

	/// <summary>
	/// Optional status description for Error status events.
	/// Only used when <see cref="GenerateActivity"/> is true, <see cref="ActivityMethodType"/> is Event,
	/// and <see cref="ActivityStatusCode"/> is Error.
	/// </summary>
	public string? ActivityStatusDescription { get; set; }

#if !EXCLUDE_PURVIEW_TELEMETRY_LOGGING

	/// <summary>
	/// Determines if Logging telemetry should be generated for this method.
	/// </summary>
	public bool GenerateLogging { get; set; }

	/// <summary>
	/// Optional log level for the Logging telemetry. Use Microsoft.Extensions.Logging.LogLevel values.
	/// Only used when <see cref="GenerateLogging"/> is true.
	/// </summary>
	public global::Microsoft.Extensions.Logging.LogLevel LogLevel { get; set; } =
		global::Microsoft.Extensions.Logging.LogLevel.Information;

	/// <summary>
	/// Optional log message template for the Logging telemetry.
	/// Only used when <see cref="GenerateLogging"/> is true.
	/// </summary>
	public string? LogMessage { get; set; }

	/// <summary>
	/// Optional event ID for the Logging telemetry.
	/// Only used when <see cref="GenerateLogging"/> is true.
	/// </summary>
	public int? LogEventId { get; set; }

	/// <summary>
	/// Optional log name for the Logging telemetry.
	/// Only used when <see cref="GenerateLogging"/> is true.
	/// </summary>
	public string? LogName { get; set; }

	/// <summary>
	/// Determines if scoped logging should be used (returns IDisposable).
	/// Only used when <see cref="GenerateLogging"/> is true.
	/// </summary>
	public bool UsesScopedLogging { get; set; }

#endif

	/// <summary>
	/// The metric type to generate when <see cref="GenerateMetrics"/> is true.
	/// </summary>
	public MetricType MetricType { get; set; } = MetricType.Counter;

	/// <summary>
	/// Optional metric name. If not specified, uses the method name.
	/// Only used when <see cref="GenerateMetrics"/> is true.
	/// </summary>
	public string? MetricName { get; set; }

	/// <summary>
	/// Optional metric unit for histogram and other metrics.
	/// Only used when <see cref="GenerateMetrics"/> is true.
	/// </summary>
	public string? MetricUnit { get; set; }

	/// <summary>
	/// Optional metric description.
	/// Only used when <see cref="GenerateMetrics"/> is true.
	/// </summary>
	public string? MetricDescription { get; set; }
}

/// <summary>
/// Defines the type of activity method for multi-target generation.
/// </summary>
public enum ActivityMethodType
{
	/// <summary>
	/// Activity start or create method that returns an Activity.
	/// </summary>
	Activity,
	
	/// <summary>
	/// Event method that adds an event to an existing Activity.
	/// </summary>
	Event,
	
	/// <summary>
	/// Context method that adds context (tags/baggage) to an existing Activity.
	/// </summary>
	Context
}

/// <summary>
/// Defines the type of metric to generate for multi-target generation.
/// </summary>
public enum MetricType
{
	/// <summary>
	/// Counter metric that tracks cumulative values.
	/// </summary>
	Counter,
	
	/// <summary>
	/// UpDownCounter metric that can increase and decrease.
	/// </summary>
	UpDownCounter,
	
	/// <summary>
	/// Histogram metric that tracks distribution of values.
	/// </summary>
	Histogram,
	
	/// <summary>
	/// Gauge metric that tracks current values.
	/// </summary>
	Gauge
}

/// <summary>
/// Combined result type for multi-target telemetry generation when both Activity and Scoped Logging are enabled.
/// This type is internal to the assembly and provides implicit conversions to Activity and IDisposable.
/// </summary>
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal readonly struct MultiTargetTelemetryResult : global::System.IDisposable
{
	private readonly global::System.Diagnostics.Activity? _activity;
	private readonly global::System.IDisposable? _scope;

	/// <summary>
	/// Initializes a new instance of the <see cref="MultiTargetTelemetryResult"/> struct.
	/// </summary>
	/// <param name="activity">The activity instance, if any.</param>
	/// <param name="scope">The logging scope instance, if any.</param>
	public MultiTargetTelemetryResult(global::System.Diagnostics.Activity? activity, global::System.IDisposable? scope)
	{
		_activity = activity;
		_scope = scope;
	}

	/// <summary>
	/// Gets the Activity instance, if any.
	/// </summary>
	public global::System.Diagnostics.Activity? Activity => _activity;

	/// <summary>
	/// Gets the logging scope instance, if any.
	/// </summary>
	public global::System.IDisposable? Scope => _scope;

	/// <summary>
	/// Implicit conversion to Activity.
	/// </summary>
	/// <param name="result">The multi-target result.</param>
	public static implicit operator global::System.Diagnostics.Activity?(MultiTargetTelemetryResult result) => result._activity;

	/// <summary>
	/// Implicit conversion to IDisposable.
	/// </summary>
	/// <param name="result">The multi-target result.</param>
	public static implicit operator global::System.IDisposable?(MultiTargetTelemetryResult result) => result._scope;

	/// <summary>
	/// Disposes both the activity and the logging scope.
	/// </summary>
	public void Dispose()
	{
		_scope?.Dispose();
		_activity?.Dispose();
	}
}