//HintName: Test.TestServiceCore.MultiTarget.g.cs
// <auto-generated>
//	This code was generated by the Purview.Telemetry.SourceGenerator
//	on {Scrubbed}.
//
//	Changes to this file may cause incorrect behaviour and will be lost
//	when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Test
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	sealed partial class TestServiceCore : Test.ITestService
	{
		readonly global::System.Diagnostics.ActivitySource _activitySource;
		readonly global::Microsoft.Extensions.Logging.ILogger _logger;
		readonly global::System.Diagnostics.Metrics.Meter _meter;

		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public TestServiceCore(global::System.Diagnostics.ActivitySource activitySource, global::Microsoft.Extensions.Logging.ILogger logger, global::System.Diagnostics.Metrics.Meter meter)
		{
			_activitySource = activitySource;
			_logger = logger;
			_meter = meter;
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void TestOperation(string userId, string internalId, int sensitiveCount, System.DateTime timestamp)
		{
			TestOperation_Activity(userId, sensitiveCount, timestamp);
			TestOperation_Logging(userId, internalId, timestamp);
			TestOperation_Metrics(userId, internalId, sensitiveCount);
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void TestOperation_Activity(string userId, int sensitiveCount, System.DateTime timestamp)
		{
			using var activity = _activitySource.StartActivity("TestOperation");
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void TestOperation_Logging(string userId, string internalId, System.DateTime timestamp)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_logger.LogInformation("TestOperation called with {userId}, {internalId}, {timestamp}", userId, internalId, timestamp);
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void TestOperation_Metrics(string userId, string internalId, int sensitiveCount)
		{
			var tags = global::System.Array.Empty<global::System.Collections.Generic.KeyValuePair<string, object?>>();
			// TODO: Implement actual metrics instrumentation for TestOperation
			// Example: _someCounter.Add(1, tags);
		}

	}
}