//HintName: Test.Complex.OrderServiceCore.MultiTarget.g.cs
// <auto-generated>
//	This code was generated by the Purview.Telemetry.SourceGenerator
//	on {Scrubbed}.
//
//	Changes to this file may cause incorrect behaviour and will be lost
//	when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Test.Complex
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	sealed partial class OrderServiceCore : Test.Complex.IOrderService
	{
		readonly global::System.Diagnostics.ActivitySource _activitySource;
		readonly global::Microsoft.Extensions.Logging.ILogger _logger;
		readonly global::System.Diagnostics.Metrics.Meter _meter;

		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		public OrderServiceCore(global::System.Diagnostics.ActivitySource activitySource, global::Microsoft.Extensions.Logging.ILogger logger, global::System.Diagnostics.Metrics.Meter meter)
		{
			_activitySource = activitySource;
			_logger = logger;
			_meter = meter;
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public Task<bool> ProcessOrderAsync(string orderId, int customerId, string correlationId, System.DateTime timestamp, string internalToken)
		{
			ProcessOrderAsync_Activity(orderId, customerId, correlationId, timestamp, internalToken);
			ProcessOrderAsync_Logging(orderId, customerId, correlationId, timestamp);
			ProcessOrderAsync_Metrics(orderId, customerId, correlationId, internalToken);
			return default;
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void ProcessOrderAsync_Activity(string orderId, int customerId, string correlationId, System.DateTime timestamp, string internalToken)
		{
			using var activity = _activitySource.StartActivity("process_order");
			activity?.SetTag("order.id", orderId);
			activity?.SetTag("customer.id", customerId);
			activity?.SetBaggage("correlation.id", correlationId?.ToString());
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void ProcessOrderAsync_Logging(string orderId, int customerId, string correlationId, System.DateTime timestamp)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_logger.LogInformation("Processing order {orderId} for customer {customerId}", orderId, customerId, correlationId, timestamp);
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void ProcessOrderAsync_Metrics(string orderId, int customerId, string correlationId, string internalToken)
		{
			var tags = new global::System.Collections.Generic.KeyValuePair<string, object?>[] {
new("order.id", orderId), new("customer.id", customerId)};
			// TODO: Implement actual metrics instrumentation for ProcessOrderAsync
			// Example: _someCounter.Add(1, tags);
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void CancelOrder(string orderId, string reason)
		{
			CancelOrder_Activity(orderId);
			CancelOrder_Logging(orderId, reason);
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void CancelOrder_Activity(string orderId)
		{
			using var activity = _activitySource.StartActivity("cancel_order");
			activity?.SetTag("orderId", orderId);
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void CancelOrder_Logging(string orderId, string reason)
		{
			if (!_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
			{
				return;
			}

			_logger.LogInformation("CancelOrder called with {orderId}, {reason}", orderId, reason);
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void IncrementOrderCount(string orderType, int count)
		{
			IncrementOrderCount_Metrics(orderType, count);
		}


		[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		private void IncrementOrderCount_Metrics(string orderType, int count)
		{
			var tags = new global::System.Collections.Generic.KeyValuePair<string, object?>[] {
new("order.type", orderType)};
			// TODO: Implement actual metrics instrumentation for IncrementOrderCount
			// Example: _someCounter.Add(1, tags);
		}

	}
}