//HintName: ActivityTelemetryCore.Activity.g.cs
// <auto-generated>
//	This code was generated by the Purview.Telemetry.SourceGenerator
//	on {Scrubbed}.
//
//	Changes to this file may cause incorrect behaviour and will be lost
//	when the code is regenerated.
// </auto-generated>

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
sealed partial class ActivityTelemetryCore : global::IActivityTelemetry
{
	readonly static global::System.Diagnostics.ActivitySource _activitySource = new("some-activity");

	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	static void RecordExceptionInternal(global::System.Diagnostics.Activity? activity, global::System.Exception? exception, bool escape)
	{
		if (activity == null || exception == null)
		{
			return;
		}

		global::System.Diagnostics.ActivityTagsCollection tagsCollection = new();
		tagsCollection.Add("exception.escaped", escape);
		tagsCollection.Add("exception.message", exception.Message);
		tagsCollection.Add("exception.type", exception.GetType().FullName);
		tagsCollection.Add("exception.stacktrace", exception.StackTrace);

		global::System.Diagnostics.ActivityEvent recordExceptionEvent = new(name: "exception", timestamp: default, tags: tagsCollection);

		activity.AddEvent(recordExceptionEvent);
	}

	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public global::System.Diagnostics.Activity? GettingItemFromCache(string key, string itemType)
	{
		if (!_activitySource.HasListeners())
		{
			return null;
		}

		global::System.Diagnostics.Activity? activityGettingItemFromCache = _activitySource.StartActivity("GettingItemFromCache", global::System.Diagnostics.ActivityKind.Internal, parentId: default, tags: default, links: default, startTime: default);

		if (activityGettingItemFromCache != null)
		{
			activityGettingItemFromCache.SetTag("itemtype", itemType);
		}

		if (activityGettingItemFromCache != null)
		{
			activityGettingItemFromCache.SetBaggage("key", key);
		}

		return activityGettingItemFromCache;
	}

	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void Miss(global::System.Diagnostics.Activity? activity)
	{
		if (!_activitySource.HasListeners())
		{
			return;
		}

		if (activity != null)
		{

			global::System.Diagnostics.ActivityEvent activityEventMiss = new(name: "cachemiss", timestamp: default, tags: default);

			activity.AddEvent(activityEventMiss);
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void Hit(global::System.Diagnostics.Activity? activity)
	{
		if (!_activitySource.HasListeners())
		{
			return;
		}

		if (activity != null)
		{

			global::System.Diagnostics.ActivityEvent activityEventHit = new(name: "cachehit", timestamp: default, tags: default);

			activity.AddEvent(activityEventHit);
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void Error(global::System.Diagnostics.Activity? activity, global::System.Exception ex)
	{
		if (!_activitySource.HasListeners())
		{
			return;
		}

		if (activity != null)
		{
			global::System.Diagnostics.ActivityTagsCollection tagsCollectionError = new();

			RecordExceptionInternal(activity: activity, exception: ex, escape: true);

			global::System.Diagnostics.ActivityEvent activityEventError = new(name: "Error", timestamp: default, tags: tagsCollectionError);

			activity.AddEvent(activityEventError);
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void Finished(global::System.Diagnostics.Activity? activity, global::System.TimeSpan duration)
	{
		if (!_activitySource.HasListeners())
		{
			return;
		}

		if (activity != null)
		{
			global::System.Diagnostics.ActivityTagsCollection tagsCollectionFinished = new();
			tagsCollectionFinished.Add("duration", duration);

			global::System.Diagnostics.ActivityEvent activityEventFinished = new(name: "Finished", timestamp: default, tags: tagsCollectionFinished);

			activity.AddEvent(activityEventFinished);
		}
	}

}
