name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release packages
    uses: purview-dev/build/.github/workflows/purview-release.yml@main
    with:
      build-version: "0.2.1"
      release-mode: NuGet
      release-branch: main
    secrets: inherit