name: Release PR

on:
  push:
    branches:
      - main

jobs:
  release-pr:
    uses: kjldev/.github/.github/workflows/release-pr.yml@main
    with:
      install-command: bun install
      version-command: bun run version-packages
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      CHANGESET_TOKEN: ${{ secrets.CHANGESET_TOKEN }}
