namespace Purview.Telemetry.SourceGenerator.Records;

#pragma warning disable format

// Attribute-data models generated by the PSGF AttributeDataModelGenerator.
// Each struct mirrors one injected marker attribute; the generated
// FromAttributeData/TryFromAttributeData members extract attribute arguments into
// equatable, cacheable values (defaults applied at extraction time).

[Generate("Purview.Telemetry.ActivitySourceAttribute")]
readonly partial record struct ActivitySourceAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("defaultToTags")] [Property(DefaultValue = true)] bool DefaultToTags,
	[Argument("baggageAndTagPrefix")] [Property] string? BaggageAndTagPrefix,
	[Argument("includeActivitySourcePrefix")] [Property(DefaultValue = true)] bool IncludeActivitySourcePrefix,
	[Argument("lowercaseBaggageAndTagKeys")] [Property(DefaultValue = true)] bool LowercaseBaggageAndTagKeys
);

[Generate("Purview.Telemetry.ActivitySourceGenerationAttribute")]
readonly partial record struct ActivitySourceGenerationAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("defaultToTags")] [Property(DefaultValue = true)] bool DefaultToTags,
	[Argument("baggageAndTagPrefix")] [Property] string? BaggageAndTagPrefix,
	[Argument("baggageAndTagSeparator")] [Property(DefaultValue = ".")] string? BaggageAndTagSeparator,
	[Argument("lowercaseBaggageAndTagKeys")] [Property(DefaultValue = true)] bool LowercaseBaggageAndTagKeys,
	[Argument("generateDiagnosticsForMissingActivity")]
	[Property(DefaultValue = true)]
		bool GenerateDiagnosticsForMissingActivity
);

[Generate("Purview.Telemetry.ActivityAttribute")]
readonly partial record struct ActivityAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("kind")] [Property(DefaultValue = 0)] int Kind,
	[Argument("createOnly")] [Property] bool CreateOnly
);

[Generate("Purview.Telemetry.EventAttribute")]
readonly partial record struct EventAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("useRecordExceptionRules")] [Property(DefaultValue = true)] bool UseRecordExceptionRules,
	[Argument("recordExceptionAsEscaped")]
	[Property(DefaultValue = true, Name = "RecordExceptionAsEscaped")]
		bool RecordExceptionEscape,
	[Argument("statusCode")] [Property(DefaultValue = 0)] int StatusCode,
	[Argument("statusDescription")] [Property] string? StatusDescription
);

[Generate("Purview.Telemetry.TelemetryGenerationAttribute")]
readonly partial record struct TelemetryGenerationAttributeData(
	[Argument("generateDependencyExtension")] [Property(DefaultValue = true)] bool GenerateDependencyExtension,
	[Argument("className")] [Property] string? ClassName,
	[Argument("dependencyInjectionClassName")] [Property] string? DependencyInjectionClassName,
	[Property(DefaultValue = false)] bool DependencyInjectionClassIsPublic,
	[Property(DefaultValue = 1)] int NamingConvention,
	[Property(DefaultValue = true)] bool GenerateTelemetryNamesClass,
	[Property] string? TelemetryNamesClassName
);

[Generate("Purview.Telemetry.TagAttribute")]
readonly partial record struct TagAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("skipOnNullOrEmpty")] [Property] bool SkipOnNullOrEmpty
);

[Generate("Purview.Telemetry.BaggageAttribute")]
readonly partial record struct BaggageAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("skipOnNullOrEmpty")] [Property] bool SkipOnNullOrEmpty
);

[Generate("Purview.Telemetry.ExcludeTargetsAttribute")]
readonly partial record struct ExcludeTargetsAttributeData(
	[Argument("targets")] [Property(Name = "ExcludedTargets")] int Targets
);

[Generate("Purview.Telemetry.LoggerGenerationAttribute")]
readonly partial record struct LoggerGenerationAttributeData(
	[Argument("defaultLevel")] [Property(DefaultValue = 99)] int DefaultLevel,
	[Property(DefaultValue = 99)] int GenerationMode,
	[Property(DefaultValue = 99)] int DefaultPrefixType
);

[Generate("Purview.Telemetry.LoggerAttribute")]
readonly partial record struct LoggerAttributeData(
	[Argument("defaultLevel")] [Property(DefaultValue = 99)] int DefaultLevel,
	[Argument("customPrefix")] [Property] string? CustomPrefix,
	[Property(DefaultValue = 99)] int PrefixType,
	[Property(DefaultValue = 99)] int GenerationMode
);

[Generate("Purview.Telemetry.LogAttribute")]
readonly partial record struct LogAttributeData(
	[Argument("level")] [Property(DefaultValue = 99)] int Level,
	[Argument("messageTemplate")] [Property] string? MessageTemplate,
	[Argument("eventId")] [Property(DefaultValue = -1)] int EventId,
	[Argument("name")] [Property] string? Name,
	[Property(DefaultValue = 0)] int GenerationMode
);

[Generate("Purview.Telemetry.ExpandEnumerableAttribute")]
readonly partial record struct ExpandEnumerableAttributeData(
	[Argument("maximumValueCount")] [Property(DefaultValue = 5)] int MaximumValueCount
);

[Generate("Purview.Telemetry.TraceAttribute")]
readonly partial record struct TraceAttributeData(
	[Argument("messageTemplate")] [Property] string? MessageTemplate,
	[Argument("eventId")] [Property(DefaultValue = -1)] int EventId,
	[Argument("name")] [Property] string? Name,
	[Property(DefaultValue = 0)] int GenerationMode
);

[Generate("Purview.Telemetry.DebugAttribute")]
readonly partial record struct DebugAttributeData(
	[Argument("messageTemplate")] [Property] string? MessageTemplate,
	[Argument("eventId")] [Property(DefaultValue = -1)] int EventId,
	[Argument("name")] [Property] string? Name,
	[Property(DefaultValue = 0)] int GenerationMode
);

[Generate("Purview.Telemetry.InfoAttribute")]
readonly partial record struct InfoAttributeData(
	[Argument("messageTemplate")] [Property] string? MessageTemplate,
	[Argument("eventId")] [Property(DefaultValue = -1)] int EventId,
	[Argument("name")] [Property] string? Name,
	[Property(DefaultValue = 0)] int GenerationMode
);

[Generate("Purview.Telemetry.WarningAttribute")]
readonly partial record struct WarningAttributeData(
	[Argument("messageTemplate")] [Property] string? MessageTemplate,
	[Argument("eventId")] [Property(DefaultValue = -1)] int EventId,
	[Argument("name")] [Property] string? Name,
	[Property(DefaultValue = 0)] int GenerationMode
);

[Generate("Purview.Telemetry.ErrorAttribute")]
readonly partial record struct ErrorAttributeData(
	[Argument("messageTemplate")] [Property] string? MessageTemplate,
	[Argument("eventId")] [Property(DefaultValue = -1)] int EventId,
	[Argument("name")] [Property] string? Name,
	[Property(DefaultValue = 0)] int GenerationMode
);

[Generate("Purview.Telemetry.CriticalAttribute")]
readonly partial record struct CriticalAttributeData(
	[Argument("messageTemplate")] [Property] string? MessageTemplate,
	[Argument("eventId")] [Property(DefaultValue = -1)] int EventId,
	[Argument("name")] [Property] string? Name,
	[Property(DefaultValue = 0)] int GenerationMode
);

[Generate("Microsoft.Extensions.Logging.LogPropertiesAttribute")]
readonly partial record struct LogPropertiesAttributeData(
	[Property] bool OmitReferenceName,
	[Property] bool SkipNullProperties,
	[Property] bool Transitive
);

[Generate("Purview.Telemetry.MeterGenerationAttribute")]
readonly partial record struct MeterGenerationAttributeData(
	[Argument("meterName")] [Property] string? MeterName,
	[Argument("nameGenerationType")] [Property(DefaultValue = 1)] int MeterNameGenerationType,
	[Argument("instrumentPrefix")] [Property] string? InstrumentPrefix,
	[Property(DefaultValue = ".")] string? InstrumentSeparator,
	[Argument("lowercaseInstrumentName")] [Property(DefaultValue = true)] bool LowercaseInstrumentName,
	[Argument("lowercaseTagKeys")] [Property(DefaultValue = true)] bool LowercaseTagKeys
);

[Generate("Purview.Telemetry.MeterAttribute")]
readonly partial record struct MeterAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("instrumentPrefix")] [Property] string? InstrumentPrefix,
	[Property(DefaultValue = true)] bool IncludeAssemblyInstrumentPrefix,
	[Property(DefaultValue = true)] bool LowercaseInstrumentName,
	[Property(DefaultValue = true)] bool LowercaseTagKeys
);

[Generate("Purview.Telemetry.CounterAttribute")]
readonly partial record struct CounterAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("unit")] [Property] string? Unit,
	[Argument("description")] [Property] string? Description,
	[Argument("autoIncrement")] [Property] bool AutoIncrement
);

[Generate("Purview.Telemetry.AutoCounterAttribute")]
readonly partial record struct AutoCounterAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("unit")] [Property] string? Unit,
	[Argument("description")] [Property] string? Description
);

[Generate("Purview.Telemetry.UpDownCounterAttribute")]
readonly partial record struct UpDownCounterAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("unit")] [Property] string? Unit,
	[Argument("description")] [Property] string? Description
);

[Generate("Purview.Telemetry.HistogramAttribute")]
readonly partial record struct HistogramAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("unit")] [Property] string? Unit,
	[Argument("description")] [Property] string? Description
);

[Generate("Purview.Telemetry.ObservableCounterAttribute")]
readonly partial record struct ObservableCounterAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("unit")] [Property] string? Unit,
	[Argument("description")] [Property] string? Description,
	[Argument("throwOnAlreadyInitialized")] [Property] bool ThrowOnAlreadyInitialized
);

[Generate("Purview.Telemetry.ObservableUpDownCounterAttribute")]
readonly partial record struct ObservableUpDownCounterAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("unit")] [Property] string? Unit,
	[Argument("description")] [Property] string? Description,
	[Argument("throwOnAlreadyInitialized")] [Property] bool ThrowOnAlreadyInitialized
);

[Generate("Purview.Telemetry.ObservableGaugeAttribute")]
readonly partial record struct ObservableGaugeAttributeData(
	[Argument("name")] [Property] string? Name,
	[Argument("unit")] [Property] string? Unit,
	[Argument("description")] [Property] string? Description,
	[Argument("throwOnAlreadyInitialized")] [Property] bool ThrowOnAlreadyInitialized
);
