namespace Purview.Telemetry.SourceGenerator.Records;

/// <summary>
/// The fully-formed, value-equatable model handed to each <c>RegisterSourceOutput</c>
/// callback and the target emitters. Provides an easy extension point for future
/// output-wide information.
/// </summary>
readonly record struct ActivityOutputContext(
	ActivitySourceTarget Target,
	GenerationContext<TelemetryCapabilities> Context
)
{
	public CodeWriter CreateWriter() => Context.CreateCodeWriter().AutoGeneratedHeader();
}

readonly record struct LoggerOutputContext(LoggerTarget Target, GenerationContext<TelemetryCapabilities> Context)
{
	public CodeWriter CreateWriter() => Context.CreateCodeWriter().AutoGeneratedHeader();
}

readonly record struct MeterOutputContext(MeterTarget Target, GenerationContext<TelemetryCapabilities> Context)
{
	public CodeWriter CreateWriter() => Context.CreateCodeWriter().AutoGeneratedHeader();
}

/// <summary>
/// The subset of the assembly-level <c>[TelemetryGeneration]</c> that governs the telemetry names.
/// Resolved straight off the compilation's assembly symbol so that an assembly with no telemetry
/// targets of its own — one that only aggregates the names of its references — can still opt in.
/// Deliberately narrower than <see cref="TelemetryGenerationAttributeData"/>: the unrelated settings
/// would needlessly invalidate the cached names when they change.
/// </summary>
readonly record struct AssemblyTelemetryNamesSettings(
	bool GenerateAttribute,
	bool GenerateClass,
	bool AggregateReferencedNames,
	string? ClassName,
	string? Namespace
);

/// <summary>
/// The telemetry names and the <c>[TelemetryGeneration]</c> settings that govern them, resolved from
/// the assembly-level attribute and the activity source and meter targets. Holds nothing but strings
/// and flags, so the pipeline caches on the names themselves rather than on the targets that produced
/// them.
/// </summary>
readonly record struct ResolvedTelemetryNames(
	EquatableArray<string> ActivitySourceNames,
	EquatableArray<string> MeterNames,
	bool GenerateAttribute,
	bool GenerateClass,
	bool AggregateReferencedNames,
	string? ClassName,
	string? Namespace
)
{
	public bool IsEmpty => ActivitySourceNames.IsEmpty && MeterNames.IsEmpty;
}

/// <summary>
/// Carries the names for one of the two telemetry-names outputs. For the
/// <c>[assembly: GeneratedTelemetryNames]</c> attribute the names are this assembly's only; for the
/// <c>TelemetryNames</c> class they already include the names aggregated from referenced assemblies.
/// </summary>
readonly record struct TelemetryNamesOutputContext(
	string AssemblyName,
	ResolvedTelemetryNames Names,
	GenerationContext<TelemetryCapabilities> Context
)
{
	public CodeWriter CreateWriter() => Context.CreateCodeWriter().AutoGeneratedHeader();
}
